### ISSUE TITLE
Egret VS Bug

### ISSUE THREAD

**Issue by vmatkarimov** [egret-labs/egret-core#103]
Error when I try to create a project from Visual Studio Enterprise 2015, Visual Studio is close automaticly. This error also appears when I try to open existing project.

#bug

**Comment by zcxp** [comment]
Hi, which version are you using? EgretVS 1.5.3 has fix a bug cause VS 2015 crash.

**Comment by vmatkarimov** [comment]
I use EgretVS 1.5.3 and Visual Studio Enterprise 2015

**Comment by vmatkarimov** [comment]
System.InvalidCastException не обработано
Message: An unhandled exception of type "System.InvalidCastException" in mscorlib.dll
Additional information: The interface is not supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE))

**Comment by zcxp** [comment]
@vmatkarimov Could you open the Windows Event Viewer (just press Win+R and run "eventvwr" ), find the error log and paste the detail here? There should be two error for the crash. Thank you

**Comment by zcxp** [comment]
@vmatkarimov My email is zhangchen@egret.com, send me a email then I can reply you ASAP.

**Comment by vmatkarimov** [comment]
@zcxp send you an email

**Comment by zcxp** [comment]
Fix at EgretVS 1.5.4
