### ISSUE TITLE
native可不可以提供个解压加载的zip文件的接口？

### ISSUE THREAD

**Issue by mzszhznn** [egret-labs/egret-core#112]
native可不可以提供个解压加载的zip文件的接口，
因为这块功能上已经做过的，如果开发者独立做的话，需要针对安卓和ios都写一个解压的处理逻辑，对开发者要求比较高。

**Comment by WanderWang** [comment]
请参考 egret 提供的 jszip 这个类库~~ 在 iOS / Android 2.5.6 以上版本已经支持

**Comment by mzszhznn** [comment]
是这样的，如果zip文件中存在一些较大的图片文件，js去取的话，只能转换为base64，转换效率会很低，如果native下直接提供接口待解压的话，就可以直接用res加载做个图片了，这种方式不需要转换数据格式,另外解压效率会提高不少。
比如加载resource/images.zip（包含1.png,2.png），这种情况下，RES加载好这个zip文件后，调用naticve的一个解压方法（例如:xxx.unzip(“resource/images.zip”)）,调用完成后，直接用RES.getResByUrl("resource/images/1.png",cb,xxx,xxx);这种方式获取图片数据。
这样模块化的项目在app上性能会提高不少，我们项目现在就是这种方式，目前解压逻辑是通过java写，然后回调给js层再去取的，但是ios又要写一遍。

**Comment by mzszhznn** [comment]
web环境下就直接调用jszip解压了。
