### ISSUE TITLE
game库MainContext类一处关键字使用错误。

### ISSUE THREAD

**Issue by fightingcat** [egret-labs/egret-core#113]
[egret-core/src/extension/game/system/MainContext.ts文件](https://github.com/egret-labs/egret-core/blob/master/src/extension/game/system/MainContext.ts)中最后两行：

delete testDeviceType1;
delete testRuntimeType1;
delete是用来删除对象属性的，这两个是局部变量，这两句是无效的，delete表达式会返回false。
另外delete会改变对象的TransitionMap，导致使用对象的JIT optimized代码bail out，应该尽量避免使用。

**Comment by WanderWang** [comment]
这两个变量是在 window 上的，并不是局部变量。这里还没有向 ES6-Module 去改造，所以都是全局变量

**Comment by fightingcat** [comment]
原来如此，居然是在module外面的……
