### ISSUE TITLE
native环境急需优化

### ISSUE THREAD

**Issue by mzszhznn** [egret-labs/egret-core#114]
自认为很冷静的人，在现有环境下调的都想砸电脑了！！！！
建议1：js层报错的时候，输出请指明具体哪个类哪一行。现在遇到一个访问空对象的值，就只提示个“字段名 of undefined“。
建议2：热更新模式，加载外部文件，给个可以设定不缓存在本机的接口。

我现在是遇到一个报错，不知道位置，然后加一堆打印。接着删除APP，重新调试，发现打印加的不够重复这种工作。我已经这样重复了上百次了，这2周就没早下班过，好不容易有点起色，他妈的现在还来个闪退。继续优化啊~~~~~~~受不了了

**Comment by WanderWang** [comment]
感谢反馈，请问您是否是将代码发布为了 game-min-native.js ?

**Comment by mzszhznn** [comment]
WanderWang居然还在，辛苦您了~
game-min-native.js有发布的。
只是我的项目全部是模块化的，真正发布为game-min-native.js只有一个空壳。
然后通过它加载系统模块和资源。

**Comment by mzszhznn** [comment]
这2周好痛苦，我们项目是准备以app为主的，所以这块对我们来说很重要。

**Comment by WanderWang** [comment]
请分析一下您的代码，我初步推测是因为 game-min-native.js 以及相关其他的js文件都被混淆了，所以看不出具体的代码行数，这个问题我们已经在着手分析解决了，预计下下个版本（2周后）会提供一个支持，如果有更新的话我会在这里告知~

**Comment by mzszhznn** [comment]
报错的代码是外部加载的，不在game-min-native.js中，其实一个一个打印肯定能找出来，只是每次都要卸载APP，或清缓存，这效率低的..

**Comment by mzszhznn** [comment]
有没有可能提前试用通道，比如更新了，直接QQ上发我一份什么的，先用着。

**Comment by mzszhznn** [comment]
加载进来后eval解析的。

**Comment by mzszhznn** [comment]
突然想起来，eval方式和进来可能是取不到类文件信息的，明天我换成src载入试试.

**Comment by mzszhznn** [comment]
script.src方式引入不行，document关键字不可用，咋整呢？

**Comment by WanderWang** [comment]
使用 require 函数，请参考 natve-loader.js


------------------
Best Regards,
王泽 (wander)
Egret Technology | 白鹭时代


原始邮件
发件人:mzszhznnnotifications@github.com
收件人:egret-labs/egret-coreegret-core@noreply.github.com
抄送:Wander Wangwander.wang@egret.com
发送时间:2015年12月23日(周三) 11:12
主题:Re: [egret-core] native环境急需优化 (#114)


script.src方式引入不行，document关键字不可用，咋整呢？

**Comment by mzszhznn** [comment]
谢谢
