### ISSUE TITLE
Mac 3.0中资源内链接404

### ISSUE THREAD

**Issue by qifeng0748** [egret-labs/egret-core#116]
资源--示例项目和第三方库链接404
http://tool.egret-labs.org/EgretEngine/doc/egret-examples-3.0.0.zip
http://tool.egret-labs.org/EgretEngine/doc/egret-game-library-3.0.0.zip

**Comment by WanderWang** [comment]
感谢反馈，我们这就修正这个问题

**Comment by xsstomy** [comment]
@qifeng0748 感谢反馈，已经修复了。

**Comment by qifeng0748** [comment]
good

**Comment by xsstomy** [comment]
@qifeng0748 你好，请问一下，这个下载地址你是从哪里获取到的？

**Comment by qifeng0748** [comment]
![image](https://cloud.githubusercontent.com/assets/2580757/12048277/0204f7ac-af14-11e5-956e-1444d5d85774.png)
示例项目、第三方库

**Comment by xsstomy** [comment]
好的。非常感谢。

**Comment by qifeng0748** [comment]
![image](https://cloud.githubusercontent.com/assets/2580757/12048624/47439d60-af18-11e5-9e96-448bf5f82028.png)
示例项目使用引擎版本不是3.0.0

**Comment by xsstomy** [comment]
收到，我们这就修复这个问题
