### ISSUE TITLE
脏矩形bug

### ISSUE THREAD

**Issue by anluo** [egret-labs/egret-core#118]
Bitmap $measureContentBounds计算的bounds未加上texture的offsetx和offsety，导致脏矩形以及点击碰撞范围计算错误

**Comment by WanderWang** [comment]
收到，正在检查这个问题

**Comment by runinspring** [comment]
请问你是在什么情况下遇到的这个问题，能给我们发个demo吗。我们在$measureContentBounds计算的bounds的时候，是根据SpriteSheet里的图片信息计算的，那个是原始图片的大小，包含了offsetx和offsety

**Comment by anluo** [comment]
那可能跟我用法有关，没使用SpriteSheet，可重现代码
var subtex: egret.Texture = new egret.Texture()
subtex._setBitmapData(sprtex._bitmapData);
subtex.$initData(this.x, this.y, this.width, this.height, this.offx, this.offy, this.sourceW, this.sourceH, this.sourceW, this.sourceH);
var bmp = egret.Bitmap();
bmp.texture = subtex;

**Comment by runinspring** [comment]
你再检查一下穿进去的这些值有没有错误，比如offx，offy不能是负的，sourceW，sourceH是计算了offsetx和offsety的最终大小
