### ISSUE TITLE
websocket bug

### ISSUE THREAD

**Issue by anluo** [egret-labs/egret-core#119]
sock.addEventListener(egret.Event.CONNECT,function(){            
            var byteData:egret.ByteArray = new egret.ByteArray();
            byteData.endian = egret.Endian.LITTLE_ENDIAN;        
            byteData.writeInt(-2);	
            byteData.writeInt(3);
            byteData.writeInt(3);
            byteData.writeInt(3);
            byteData.writeInt(3);
            byteData.writeInt(3);
            byteData.writeInt(3);
            byteData.writeUTF("login");	
            sock.writeBytes(byteData, 0, byteData.bytesAvailable);
            sock.flush();
        },this); 
这段代码如果第一个writeInt是-1时，在firefox43.0.3和runtime下发出的数据包会错乱

**Comment by h-wei** [comment]
这一块不知道你的服务器地址是多少？我们使用ws://echo.websocket.org/测试了以上的代码，发现是正确了的。以下为输出的log：

01-11 11:26:15.055: D/EgretRuntimeC(15318): EGTV8WebSocket:onopen
01-11 11:26:15.055: I/EgretRuntimeC(15318): [JS]:onopen ===
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:254
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:255
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:255
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:255
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:3
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:3
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:3
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:3
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:3
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:3
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:5
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:108
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:111
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:103
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:105
01-11 11:26:15.095: I/EgretRuntimeC(15318): [JS]:110
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:onmessage ===
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:254
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:255
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:255
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:255
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:3
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:3
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:3
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:3
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:3
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:3
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:5
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:0
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:108
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:111
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:103
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:105
01-11 11:26:15.475: I/EgretRuntimeC(15318): [JS]:110

**Comment by anluo** [comment]
这个跟服务器无关，我们在Windows Firefox环境下抓包分析，数据就是错的，chrome和ie正常。其实2.5之前版本都是好的，引擎升级之后就不正常了，猜测是你们对ByteArray writeBytes做的优化导致的。

**Comment by h-wei** [comment]
好的，我们看一下你说的这一块，有个疑问就是我这一块为什么是对的，不能模拟出来你的环境

**Comment by himuil** [comment]
请问下，现在有问题的版本号是多少？我们查一下

**Comment by anluo** [comment]
egret3.0

**Comment by himuil** [comment]
ok，你可以看到引擎底层代码的writeBytes方法中，会有一段setFloat64的for循环，可以试试把这里注释了看看还会不会异常。这个优化是为了提升速度的，没准这里会有浏览器兼容问题

**Comment by himuil** [comment]
引擎层已避免使用这种方式
