### ISSUE TITLE
addEventListener thisObject问题

### ISSUE THREAD

**Issue by 06wj** [egret-labs/egret-core#120]
目前addEventListener需要传入thisObject，这个与as3或者dom里的addEventListener api差异都挺大的
是否可以改成不传thisObj，让有绑定this需求的开发者自己bind下。。

例如
```
this.stage.addEventListener(egret.TouchEvent.TOUCH_BEGIN,this.onTouchHandler.bind(this));
```

**Comment by himuil** [comment]
这里应该不会做修改的，如果感觉使用不顺手可以自己封装一个全局函数去处理这个
