### ISSUE TITLE
官网出现死循环跳转

### ISSUE THREAD

**Issue by zbinlin** [egret-labs/egret-core#127]
页面：http://www.egret.com/en/

看到页面的源码里在有些地方把 `x11` 写成 `xll`，从而导致死循环了 :)

在 linux 下浏览器的 lang 为 en-US 下可重现。

**Comment by zerlot** [comment]
感谢，我们这就排查。

**Comment by xinfangke** [comment]
感谢，问题已修复，请尝试访问 http://www.egret.com/en/  。
