### ISSUE TITLE
Confusing "magic number" on GraphicsNode#beginGradientFill? (819.2)

### ISSUE THREAD

**Issue by endel** [egret-labs/egret-core#139]
Hi there,

First of all, thanks for developing such an open-source library!

Not sure this is the best place to ask questions, as the forums are mostly in Chinese, I can't really use that :)

Is there an explanation when multiplying by `819.2` on [GraphicsNode#beginGradientFill](https://github.com/egret-labs/egret-core/blob/f7cf90dd4c9d60cd3182026c8222ccd55033e8a4/src/egret/player/nodes/GraphicsNode.ts#L79-L82)? I found that rather confusing.

I'm having to do the reverse operation here to achieve the expected results. E.g.:

```javascript
this.beginGradientFill(
  egret.GradientType.LINEAR,
  colors,
  alphas,
  ratios.map(ratio => ratio * 255),
  new egret.Matrix(1, x0 / 819.2, 1, y0 / 819.2)
);
```

Thanks again for the great work.

**Comment by himuil** [comment]
1638.4 is a matrix scaling factor in Flash. You can use the generator matrix method egret.Matrix.createGradientBox.

**Comment by endel** [comment]
Thanks for clarifying!
