### ISSUE TITLE
Not able to centralize text (egret.HorizontalAlign.CENTER)

### ISSUE THREAD

**Issue by endel** [egret-labs/egret-core#140]
Using `textfield.textAlign = egret.HorizontalAlign.CENTER` is not centralizing the text. Am I missing something? 

```ts
var textfield = new egret.TextField();
textfield.type = egret.TextFieldType.DYNAMIC;
textfield.textAlign = egret.HorizontalAlign.CENTER;
textfield.x = this.stage.stageWidth / 2;
textfield.y = 135;
textfield.text = "This text is not being centralized";
this.addChild(textfield);
```

Shouldn't the "anchor" of the `TextField` be placed at the center of the DisplayObject?

Thanks,
Endel

**Comment by WanderWang** [comment]
```textfield.width = 300``` , please :-)

**Comment by endel** [comment]
Thanks @WanderWang!

The behaviour on egret is different than in other libraries such as PIXI. Just found the documentation here: http://edn.egret.com/cn/docs/page/144

**Comment by WanderWang** [comment]
Unfortunately , "anchor" API have conflict with egret's dirty-region-rendering system . So we remove anchor API since egret 2.5
