### ISSUE TITLE
CreateJS to egret-core bridge available?

### ISSUE THREAD

**Issue by endel** [egret-labs/egret-core#141]
Hi egret team,

Is there a full-featured CreateJS bridge available out there? As I couldn't find, I've published my own here, which is based on [PixiFlash](https://github.com/CloudKidStudio/PixiFlash).
- Source: http://github.com/endel/egret-animate
- Demo: http://endel.github.io/egret-animate

Things to note on this example
- radial gradients are not fully working
- rotation around a point is not working (for the hat; egret doesn't have a "anchor" feature)

**Comment by WanderWang** [comment]
Great jobs ! I'll take a look your source and find out a way to implement rotation with anchor.

By the way , egret have a " anchorOffsetX " api based on coordinate .

Can you implement rotation with anchor via coordinate , not percent ?

**Comment by endel** [comment]
Thanks for the tip @WanderWang! Rotation is working now. Gradients still are kinda tricky for me. Any help would be really appreciated! :)
