### ISSUE TITLE
Install it as a node module

### ISSUE THREAD

**Issue by endel** [egret-labs/egret-core#143]
Hi there,

It would be great to be able to install `egret-core` as a node_module. Would be great to include it in a modern build tool such as webpack.

I saw that there's a pretty old version of it [here](https://www.npmjs.com/package/egret), but it's not up to date.

Cheers,
Endel

**Comment by fightingcat** [comment]
vote +1. right now I can install it through a tarball or repo path, but it can't be required.

**Comment by jiehwa** [comment]
这个老外的issue你们应该关注下，这也是大部分想构建自己工作流的开发者共同希望的，希望你们可以重视下。

**Comment by fightingcat** [comment]
没用的，官方都不看issue……

**Comment by fightingcat** [comment]
没用的，都没人看issue……

**Comment by jixingliang** [comment]
egret小白，之前干前端的，干egret两个月，这老板不签合同不交住房公积金工资很低，请问各位现在过得如何，有没有比我惨的

**Comment by kokokele** [comment]
起码支持npm包的形式吧。 这样给egret扩展也容易些。 egret才能更加繁荣。

**Comment by newbienewbie** [comment]
@WanderWang  冒昧的问一句，这个issuue 短期解决的可能性大吗？

**Comment by fightingcat** [comment]
@newbienewbie 即将解决了，egret5已经重构了，等5发布吧。

**Comment by kokokele** [comment]
期待，大概时候发布啊？

**Comment by fightingcat** [comment]
@kokokele 说是这周来着谁知道呢，等着吧，反正是改了
