### ISSUE TITLE
No mouseover / mouseout support?

### ISSUE THREAD

**Issue by endel** [egret-labs/egret-core#144]
Hi again,

I was looking through the code and documentation and couldn't find a way to implement `mouseover` / `mouseout` event for display objects.

There is a [`TOUCH_ROLL_OVER`](http://edn.egret.com/en/index.php/apidoc/index/name/egret.TouchEvent#TOUCH_ROLL_OVER), event, which seems to be already deprecated.

Am I missing something? Cheers!

**Comment by himuil** [comment]
https://github.com/egret-labs/egret-game-library/tree/master/mouse

This should be what you want.

**Comment by endel** [comment]
Thanks @himuil. That's exactly what I was looking for.
