### ISSUE TITLE
linux上使用egret命令

### ISSUE THREAD

**Issue by jinceon** [egret-labs/egret-core#154]
我想在linux服务器上使用egret build, egret publish等命令。
因为我只想把ts代码上传到git仓库。所以我想在服务器端build。

**Comment by vollen** [comment]
你在linux 上运行的话， 是会出现 “Unsupported locale zh_CN”吧.
我这边也遇到了， 问题出在*nix系统会区分大小写， 而typescript工具在查找字符集的时候， 将字符集全都转换成小写了。 而字符集的目录则是 zh_CN的， 所以找不到。

你需要打开 /tools/lib/typescript/tsclark.js, 然后找到`validateLocaleAndSetLanguage()`方法， 然后将第一行代码改为
```
        var matchResult = /^([A-Za-z]+)([_\-]([A-Za-z]+))?$/.exec(locale);
```
然后在项目目录下运行 `node <egret-core目录>/tools/bin/egret build` 就可以了。

**Comment by WanderWang** [comment]
感谢楼上的解决方案，4.0 官方也会按照类似的方法去解决这个问题
