### ISSUE TITLE
设置动画中心点？

### ISSUE THREAD

**Issue by slyang520** [egret-labs/egret-core#155]
//我通过这种方式  来设置动画中心点无效  egret设置动画中心究竟是通过什么样的方式 
var myMatrix: egret.Matrix = this.btn3Test.matrix;
        let test2: egret.Point = myMatrix.transformPoint(this.btn3Test.width / 2, this.btn3Test.height/2);
        this.btn3Test.matrix = myMatrix;
        this.addChild(this.btn3Test);

**Comment by eos3tion** [comment]
@slyang520 
白鹭的DisplayObject有`anchorOffsetX`,`anchorOffsetY`你的需求，用这两个属性可以解决。

**Comment by panlimin** [comment]
@WanderWang 楼上正解，可以关闭该问题
