### ISSUE TITLE
textfield 如何获取文本块的Boundary，以及如何设置letterSpace和leading？

### ISSUE THREAD

**Issue by Tomyail** [egret-labs/egret-core#156]
用flash的textfild作图文混排，非常依赖api提供的setTextFormat，getLineOffset，getLineIndexOfChar，getCharBoundaries。

1. 请问egret有能力设置特定行的行间距(leading)和字符间距(letterSpace)吗，类似textfield通过setTextFormat给指定行设置leading？egret的textfield提供的`lineSpacing`似乎无法满足需求。
2. textfield里面的`getCharBoundaries `,有对应的实现吗?

**Comment by eos3tion** [comment]
@Tomyail 
使用
`egret.sys.measureText`  
或者直接使用
`CanvasRenderingContext2D.prototype.measureText`  
来获取文本高度和宽度
`flash`并未直接提供类似api  
至于你需要的setTextFormat，getLineOffset，getLineIndexOfChar，getCharBoundaries 都可以自己计算
