### ISSUE TITLE
什么时候能将tsserver，tsc更新至2.x+

### ISSUE THREAD

**Issue by eos3tion** [egret-labs/egret-core#157]
目前egret-core不支持大量`typescript 2.x`的特性。  
1.8.9的一些特性也支持的不全，比如literal-string autocomplete  
我目前egret项目的开发已经放弃使用egret-wing转用vscode 
配置egret build编译，用Chrome调试了，但是有些如 2.0的` readonly `特性，class中的`optional properties`的报错很容易干扰开发

**Comment by runinspring** [comment]
下周发布的3.2.6会把tsc升级到2.1.4
