### ISSUE TITLE
使用EgretWing编译项目，有4个文件必须手动生成，希望可以改为自动生成

### ISSUE THREAD

**Issue by Raykid** [egret-labs/egret-core#162]
这4个文件是：

1. index.html
2. libs/exml.d.ts
3. resource/default.thm.json
4. template/runtime/native_require.js

问题是这样的，这4个文件必须手动生成，之后会被编译器接管自动更新，如果不先手动生成，则编译器无法自动生成之。造成的问题是：

1.我使用git进行管理，希望在提交版本的时候忽略这4个文件，希望用.gitignore文件管理这4个文件，以让所有人在提交时不要提交这4个文件；
2. 但是.gitignore文件只能对不受版本控制的情况下生效，已列入版本控制的文件无法生效；
3. 如果不将这4个文件列入版本控制，则所有人在clone下来后无法生成这4个文件，就导致编译之后无法运行，原因就是上文提到的编译器无法自动生成。

因此陷入了死循环，既不能让这4个文件列入git版本控制（.gitignore不生效），又不能不列入控制（新clone下来没有这4个文件，导致无法运行）。唯一打破这个死循环的就是让编译器在发现这4个文件不存在时自动生成之。

**Comment by WanderWang** [comment]
非常感谢您的建议，我认为您说的非常有道理，我们会在白鹭引擎未来的版本中重点考虑您这个想法！
