### ISSUE TITLE
WebGLRenderer类getRenderCount方法会造成崩溃

### ISSUE THREAD

**Issue by flypart** [egret-labs/egret-core#170]
复现场景：
EUI项目中，场景中有一个group，group下面有一个eui.Button和一个eui.BitmapLabel。给group加上一个filter，就会崩溃。

WebGLRenderer类中的第298行
`childrenDrawCount += node.$getRenderCount();`
node变量有可能是null，会造成崩溃。

在这一行之前加一个判断
`if (node)`
可以解决这个问题。

**Comment by himuil** [comment]
master分支已经修复这个问题，感谢反馈
