### ISSUE TITLE
文件引用错误

### ISSUE THREAD

**Issue by TLDay** [egret-labs/egret-core#173]
使用egret make编译引擎时出现该错误
```
/usr/local/lib/node_modules/egret/src/extension/resource/Resource.ts(43,1): error TS6053: File '/usr/local/lib/node_modules/egret/src/extension/resource/version/HTML5VersionController.ts' not found.
/usr/local/lib/node_modules/egret/src/extension/resource/Resource.ts(43,1): error TS6053: File '/usr/local/lib/node_modules/egret/src/extension/resource/version/HTML5VersionController.ts' not found.
```
/src/extension/resource/Resource.ts中对HTML5VersionController.ts的引用中HTML为纯大写，实际上应为Html5VersionController.ts。

**Comment by TLDay** [comment]
库来自于github上最新的 release:`v4.0.3`
下载后使用npm install -g安装，当使用egret make命令时出现该错误。

**Comment by TLDay** [comment]
本地引擎没有这个问题。应该只发生在github上release的包里，可能你们本地修改了，但是仓库没有改动。可能是这个问题导致的：
http://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git
http://stackoverflow.com/questions/8904327/case-sensitivity-in-git

**Comment by TLDay** [comment]
https://github.com/egret-labs/egret-core/blob/master/src/extension/resource/Resource.ts#L43

**Comment by himuil** [comment]
master分支已修改，感谢反馈
