### ISSUE TITLE
升级4.1后，使用`egret create_lib`新建的第三方库，编译会报错

### ISSUE THREAD

**Issue by eos3tion** [egret-labs/egret-core#174]
```shell
e:\test>egret create_lib a123
您正在使用的引擎版本为 4.1.0

e:\test>cd a123

e:\test\a123>egret build
您正在使用的引擎版本为 4.1.0
正在编译项目...
第三方库编译报错，您可以访问http://developer.egret.com/cn/github/egret-docs/Engine2D/projectConfig/libraryProject/index.html了解详情
白鹭引擎 4.1 使用新结构进行第三方库升级，请先升级您的第三方库

e:\test\a123>
```

另外`http://developer.egret.com/cn/github/egret-docs/Engine2D/projectConfig/libraryProject/index.html`这个页面没有内容

**Comment by eos3tion** [comment]
`https://github.com/egret-labs/egret-docs/tree/master//Engine2D/projectConfig/libraryProject/`
这个页面的README.md到是找到内容了。但是你们官网貌似没同步

**Comment by eos3tion** [comment]
另外第三方插件对`DEBUG`和`RELEASE`标签处理方式不一致。
4.0.3的处理方式为： xx.js继续保留 `DEBUG`或者`RELEASE`标签  
4.1.0的处理方式，会直接将`DEBUG`替换为`true`，导致生成`xx.min.js`文件时，原本会被移除的代码，会继续保留在min文件中
![image](https://cloud.githubusercontent.com/assets/8804051/26340379/a0808ec6-3fc0-11e7-97fb-ac599a3fbd6e.png)

**Comment by himuil** [comment]
4.1附近这块确实有些混乱，最新版5.0.2应该已经全部修复了，麻烦验证一下

**Comment by eos3tion** [comment]
@himuil 刚刚测试了  5.0.2  
`DEBUG` 标签还是会直接被替换成 `true`，和4.1.0一样，xx.min.js会保留 `DEBUG` 块中的代码
