### ISSUE TITLE
设置retina参数对解决字体模糊问题不是个合适方案

### ISSUE THREAD

**Issue by babyzone2004** [egret-labs/egret-core#176]
原帖提到的字体模糊问题：http://bbs.egret.com/thread-26362-2-1.html
我看了commit：https://github.com/egret-labs/egret-core/commit/6f28acf8c4b4bc9f75e7008886094345022d9e10

通过放大canvas再缩小，虽然能解决问题，但属于间接解决的方法，应该从textfiled上解决。
举个场景，720*1280的canvas在720*1280的屏幕上显示一段问题，本身就不应有模糊的情况。
现在解决方案是直接把尺寸拉大到1440*2560再通过css缩小，问题是解决了，但占用的显存呈数量级增加。希望作者能从根源上把这个问题处理一下

**Comment by babyzone2004** [comment]
麻烦关注一下这些细节问题

**Comment by himuil** [comment]
这个问题本质的解决方案就是要放大canvas的，你可以查一下devicePixelRatio相关资料

**Comment by babyzone2004** [comment]
确实是要放大，但很多游戏，自己会手动已经放大一次，应该也能避免模糊才对

**Comment by himuil** [comment]
@babyzone2004 自己手动放大文本不是本质在解决这个问题的，本质解决必须放大canvas的，可以参考：https://www.khronos.org/webgl/wiki/HandlingHighDPI

**Comment by babyzone2004** [comment]
我说的就是自己手动放大canvas，例如我用720*1280宽度的canvas，在720的显示屏应该是清晰的，但实际上不清晰。你可以试试

**Comment by himuil** [comment]
@babyzone2004 对呀，如果devicePixelRatio不是1的话，这样就是不清晰的。所以我们retina参数是要放大canvas的，没有错误。没太理解你纠结在哪里

**Comment by babyzone2004** [comment]
并不是这样的，我指的是720*1280分辨率的设备。
举个例子，小米2是720*1280分辨率，devicePixelRatio是2。实际css尺寸是**360*640**。
如果我写一个360px*640px的canvas，可以在手机上刚好全屏，但是会模糊，因为实际拉大了。
但我手动写一个720px*1280px的canvas，通过css设置宽高为360px*640px，这种情况，是不会模糊的。
实际上你们retina方案也是这个原理。

我提的问题是，手动写了720px*1280px的canvas，并且设置宽高为360px*640px，这种写法是可以保证清晰度的，但是egret会出现模糊。如果需要我可以提供一个demo

**Comment by himuil** [comment]
@babyzone2004 “手动写了720px1280px的canvas，并且设置宽高为360px640px”，这个操作好像本身不是egret支持的吧，egret的屏幕适配方案我记得没有这样的

**Comment by babyzone2004** [comment]
egret可以配置canvas宽高(data-content-width)。css是egret自动适配的，实际情况会适配到360px*640px

**Comment by himuil** [comment]
@babyzone2004 可是style里面的不一定永远是360x640，你可以判断360x640的机器不用retina。比这个大的用retina的
