### ISSUE TITLE
编译问题覆盖index.html

### ISSUE THREAD

**Issue by SangLiang** [egret-labs/egret-core#190]
wing版本4.0.3
引擎版本5.0.4
在修改完index.html的选项之后，如fps的值，入口函数，然后修改其他的文件，编译文件运行，有很大的概率会用初始文件覆盖掉我们修改的index.html，建议有单独的json文件来做配置。

**Comment by jumpcat** [comment]
http://developer.egret.com/cn/2d/projectConfig/tempfile
直接修改 debug/index.html 就可以了， web/index.html 还有点问题，我已经提交了一个 pull request
