### ISSUE TITLE
[BUG]ByteArray.prototype.readUTF无法正确解析 ByteArray.prototype.writeUTF的字符串

### ISSUE THREAD

**Issue by eos3tion** [egret-labs/egret-core#192]
测试代码：
```typescript
let a = ["123","abc","def"];
let spStr = String.fromCharCode(0);
let m = a.join(spStr);
let ba = new ByteArray();
ba.writeUTF(m);
ba.position=0;
let mout = ba.readUTF();
let aout = mout.split(spStr);
```
输入数据和输出数据无法对应
aout的结果就会完全不对，变成：["123abcdef"]

bug产生原因，decodeUTF方法中，
https://github.com/egret-labs/egret-core/blob/master/src/egret/utils/ByteArray.ts#L1087
```typescript
if (code_point > 0)
```
判断为多余

unicode中 0 表示 `空字符`，会占位，并不完全等于 `""`

https://baike.baidu.com/item/ASCII/309296?fr=aladdin#3

25ac1ef

**Comment by himuil** [comment]
这段代码在Flash中是遇到0就强制终止了，最终返回"123"，egret中是忽略了0。
每个引擎都有自己对于这种逻辑的处理，不能强制算是bug吧，只能算是策略而已。

**Comment by eos3tion** [comment]
@himuil 
Adobe主导的`ES4.0`标准早被`弃用`了。
你们现在的 `decodeUTF` 方法都无法和浏览器原生的
`TextDecoder`兼容，另外和自身的`encodeUTF`方法都不是互逆方法，这难道不算`bug`么？
如果说`白鹭`引擎，就是不支持 字符串中有`CodePoint`为`0`的值，好歹`encodeUTF`方法里面也做个处理吧。
目前这块的代码是，可以将字符串中带`CodePoint`为`0`的值进行 序列化，会实际占用字节，但是无法反序列化。

**Comment by eos3tion** [comment]
@himuil 
另外那个`demo`，的使用方式肯定是有问题的，准确说是`demo`的作者对`ArrayBuffer`的理解有问题，如果他不是纯字符串，而是其他二进制数据，按他的处理方式，本身也会出错。

**Comment by himuil** [comment]
@eos3tion Flash也是不能互逆的，大家用了10年也没人说这是bug的吧，一个约束而已。如果特别想用浏览器那套，可以封装一个方法，直接把字节流取出来自己调用浏览器的。

**Comment by eos3tion** [comment]
@himuil  Flash是 AVM的pushString做的处理。
也就是如你所说，`a = ["123","abc","def"];`在调用 `a.join(spStr)`，`AVM`进行 `OPCODE  0x2C(PushString)`操作 时，已经让 `m` 变成了 `"123"`
所以AS3中的`ByteArray`的`writeUTF`和`readUTF`，序列化和反序列化是一致的。
即输入等于输出值。
输入是`"123"`，输出也是`"123"`。

很可惜 ES5 的字符串标准，是允许 `CodePoint` 为 `0` 的值
这样白鹭的`writeUTF`和`readUTF` 输入输出如果按 AS3的处理，必然会出错。
因为输入是`"123\x00abc\x00def"`，但是输出是`"123abcdef"`。

**Comment by himuil** [comment]
@eos3tion 你的项目要是有需求按照我上面那样修改，或者重写引擎这俩方法吧。这个改动涉及太底层了，上版本改了之后很多开发者反馈不兼容了。有的开发者用的第三方库要改，有的开发者后端服务器要改。引擎重要的是向下兼容，这个改的实在不能接受。

**Comment by eos3tion** [comment]
@himuil 我不是纠结的问题并不是 `字符串标准`，而是白鹭的 ByteArray库，对应字符串的序列化writeUTF和反序列化readUTF，目前没有一致性。我是认为这一点有bug。
在我看来，白鹭的 字符串标准，可以是不允许有 `"\x00"`这样的字符串，但是如果 writeUTF的时候，输入了这样的字符串，不抛`异常`是有问题的。  
我认为白鹭是可以按 Flash那套字符串标准处理，但是writeUTF需要有对应的字符串检查，发现"\x00"需要`throw Error`
这样可以保证 ` writeUTF` 和 `readUTF` 的一致性。

**Comment by himuil** [comment]
@eos3tion 抛异常就不向下兼容了，开发者还是要改很多东西，这是不行的

**Comment by eos3tion** [comment]
@himuil 按白鹭的标准，字符串中是没有`"\x00"`啊，如果是`AS3`转 `H5`开发的，本身也不可能用到"\x00"啊。
这个只对，新的纯"H5"开发者有影响。但是如果新的"H5"开发者按现有的代码执行。
也就可能写出我上面那个例子，这样一定会出错啊。
在 `writeUTF` 中加验证，并完善`writeUTF`的注释，必然不会影响原有项目的。

**Comment by himuil** [comment]
@eos3tion 你还是在自己分支，或者直接改引擎源码解决下吧，这两次ByteArray的改的引起了太多的不兼容了。引擎不能总这么不稳定的

**Comment by eos3tion** [comment]
@himuil 也就是这个 `字符串序列化反序列化 不一致的问题` 只能当成`历史遗留问题`咯
