### ISSUE TITLE
[建议]将 AudioContext 中的`alert`改为抛事件，或者`console.error`

### ISSUE THREAD

**Issue by eos3tion** [egret-labs/egret-core#193]
https://github.com/egret-labs/egret-core/blob/master/src/egret/media/web/WebAudioSound.ts#L87

中有个`alert`，目前做的h5项目，如果用户，音频流加载失败，会弹系统`alert`窗口，用户会以为程序出现问题。  

建议将此 `alert` 改为抛事件或者直接使用`console.error`输出

**Comment by Sciocco** [comment]
agree
