### ISSUE TITLE
default.thm.json文件被清空的解决方案

### ISSUE THREAD

**Issue by flypart** [egret-labs/egret-core#194]
本来想发在官方论坛的，但是有关键字不合法， 所以发在这里了。

今天在开发的时候，打包发布了一次工程后，default.thm.json这个文件竟然被完全清空，里面只有"exmls":[]这一行字，非常的诡异。
我暂时还没有尝试复现这种状况，个人怀疑是打包过程中有文件加了锁导致读取或者写入失败，然后编译过程中读写文件失败、直接退出造成的。

因为我看到论坛有人也遇到了相似的问题
【http://bbs.egret.com/forum.php?m ... ht=default.thm.json】
保不准以后还会有人遇到，所以分享一下遇到这种状况我的解决方案。

这个问题出现后，无论你再怎么clean或者重装，都是没有用的，因为原来这个文件中是含有一行字的：
"autoGenerateExmlsList": true,
如果没有这行字，那么引擎在编译过程中不会再对default.thm.json这个文件进行更改。
具体逻辑可以去读引擎的源代码exml.eui.ts文件129行。
所以如果你想让这个文件重新生成，必须再加入这行字（"autoGenerateExmlsList": true）才可以。

但是实际上，这个时候你还是丢失了很多信息，例如，如果你曾经写了字体的style在这个文件中，
"styles": {
    "outline2": {
      "textColor": "0xF5F3DF",
      "fontFamily": "Microsoft YaHei",
      "stroke": 2,
      "strokeColor": "0x312314"
    },

那么这些信息也肯定是丢失了。唯一有用的做法还是重新从git或者svn上把老的文件找出来，还原一下。

在这里我想提个小建议，目前这种设计个人觉得很不妥，因为default.thm.json这个文件在build的过程中，
既要读取里面的内容来决定是否对其做修改（读取autoGenerateExmlsList），又要对它读取并重写，
同时用户又可以自行往里面添加和修改内容。

那么只要因为某些原因（例如编译中断等等）导致这个文件被清空的话，那用户写入的信息必然就丢失了。
建议官方还是把程序自动生成的文件单独提出来，clean的时候可以放心删除；而autoGenerateExmlsList这种配置项还是放到
egretProperties.json这种地方。

**Comment by Wheandis** [comment]
我也遇到过这样的情况，其中一个原因便是 default.thm.json 文件的格式不正确，比如多了个逗号或者出现相同的key。在合并代码之后，要注意检查这个文件是否有出现错误。确保无误后，再进行编译和发布。

**Comment by aqw012** [comment]
今天遇到了，不停的清空这个文件。引擎5.0.7。可怜我还是一个萌新，被虐成这样

**Comment by WanderWang** [comment]
感谢您反馈的这个问题，在 5.1.1 解决其他问题的过程中，我无意中找到了这个 BUG 的本质原因并解决了。您确认一下您是不是 Windows设备、EXML文件很多，并且很可能有固态硬盘。

您说的确实很有道理，这是一个错误的设计，resource中不应该在 build 过程中修改自身，5.1.1 新版本已经彻底修复了这个问题，您可以升级，或者等待我们下个版本把该功能合并到 5.0.x 中
