### ISSUE TITLE
[BUG] eui.BitmapLabel存在资源加载错误的bug

### ISSUE THREAD

**Issue by lava-hammer** [egret-labs/egret-core#195]
在eui.BitmapLabel中$parseFont方法里, 有如下代码:
```
getAssets(font, (bitmapFont) => {
    this.$setFontData(bitmapFont);
})
```
当连续设置字体为A和B, 且AB都没有预加载的资源时, 由于异步原因可能导致B回调先执行,再执行A回调.
那么此时的字体将显示为B, 但是实际内容为A. 
解决方法可以是在执行的时候判断一下当前完成的资源和最后设置的资源是否匹配.

**Comment by himuil** [comment]
非常感谢反馈，已经在master分支修复这个问题
https://github.com/egret-labs/egret-core/commit/96a609e064abb1dd55b864e7fb50d3e30f6df9a1
