### ISSUE TITLE
Wasm项目使用中的一些问题

### ISSUE THREAD

**Issue by joseelin** [egret-labs/egret-core#197]
一、eui.Rect 没有渲染
  【效果】占位，触摸事件都有效果；但背景一直透明
  【环境】mac+Safari11，mac+Chrome60，ios+Safari11，android+Chrome60

二、eui缓动动画锚点问题
 【效果】设置对象horizontalCenter=0，Tween动画改变对象属性ScaleX，非Wasm项目是从中间向两边放大，Wasm是从左往右
 【环境】mac+Safari11，mac+Chrome60，ios+Safari11，android+Chrome60

三、Bitmap对象渲染问题
 【效果】Bitmap对象未渲染或者变形
 【环境】Win764+Chrome59,Chrome60 WinServer2000+Chrome60

**Comment by himuil** [comment]
问题1已经修复，会在5.0.9版本解决
问题2和问题3方便提供一个demo帮助我们排查一下问题么？
demo可以发我邮箱：jerry.lin@egret.com

**Comment by joseelin** [comment]
关于问题2：由于期间 pull过最新的代码后，问题未再重现。
关于问题3：
```
egret create test --type wasm    
cd test    
egret startserver
```
![368c33647735d05a413b90acc35056dc](https://user-images.githubusercontent.com/11769337/31306098-4eb2954a-ab7b-11e7-909d-efd692f75d9d.png)
**Windows 截图**
![jietu](https://user-images.githubusercontent.com/11769337/31306100-5dbfde6c-ab7b-11e7-9c7f-d77bfe4c4539.png)
**Mac 截图**
