### ISSUE TITLE
lib/utils.js里有读取error_code.json，但是没有error_code.json这个文件

### ISSUE THREAD

**Issue by jinceon** [egret-labs/egret-core#200]
我执行了一下 egret -h，报了个错ENOENT: no such file or directory, open '/data/soft/egret-core/tools/error_code.json'

`[root@iZ286nb9ihsZ tools]# egret -h
How to use: egret <command> [-v]

command list:

    create                        Create a new project

    build                         Compile the TypeScript files in project

    publish                       Publish the project, ues GoogleClosureCompiler to compress the code

    startserver                   Start HttpServer, run the project in you browser

    clean                         Reset the Egret engin code in the project

    create_lib                    Create a new third part library

    create_app                    Create a native app form Html5

    upgrade                       Upgrade the project code

    make                          Rebuild the Egret engine source code

    info                          Get information of the Egret engine

    apitest                       Check the api was replaced or not after upgrade engine. Only for the 2.4(or before) upgrade to 2.5(or later).Use this command in 2.5(or later) project

    Use egret help <command> to understand details of each command

    (node:18769) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open '/data/soft/egret-core/tools/error_code.json'
`

我在代码里搜索error_code.json，发现 
var error_code_filename = path.join(__dirname, "../error_code.json");
var errorcode = file.readJSONSync(error_code_filename, { "encoding": "utf-8" });

但是没有error_code.json这个文件

**Comment by WanderWang** [comment]
感谢反馈，最新版本已经解决此问题，下个版本就会修复

**Comment by joesonw** [comment]
@WanderWang 尝试了v5.0.13, 还是不行. 官方有没有计划推出一个linux版本的编译环境呢?官网没有任何文档提示.这样做CI不太方便.

**Comment by lxlneo** [comment]
强烈要求支持啊 也碰到这个问题了
