### ISSUE TITLE
an incorrenct filled grid issue

### ISSUE THREAD

**Issue by DickLoong** [egret-labs/egret-core#202]
step 1:
create a TestGrid
class GridSprite extends egret.Sprite
{
    public constructor()
    {
        super();
        this.drawGrid();
    }
    private drawGrid()
    {
        var colour1:number = 0x0000ff;
        var colour2:number = 0xff0000;
        for(var j:number = 0 ;j < 10 ; j ++){
           for(var i:number = 0 ; i < 10 ; i ++){
               var actualColour = (i + j)%2 > 0 ? colour1:colour2;
                this.graphics.beginFill( actualColour );
                this.graphics.drawRect( i * 50, j * 50, 50,50 );
                this.graphics.endFill();
                 console.log("print first rect finished|" + j + "|" + i + "|" + actualColour + "|" + (i + j)%2);
           }
        }
    }
}

then paint it when during  onResourceLoadComplete

///////////////////////////////////////

/**
     * preload资源组加载完成
     * Preload resource group is loaded
     */
    private onResourceLoadComplete(event: RES.ResourceEvent) {
        if (event.groupName == "newPreload") {
            this.stage.removeChild(this.loadingView);
            RES.removeEventListener(RES.ResourceEvent.GROUP_COMPLETE, this.onResourceLoadComplete, this);
            RES.removeEventListener(RES.ResourceEvent.GROUP_LOAD_ERROR, this.onResourceLoadError, this);
            RES.removeEventListener(RES.ResourceEvent.GROUP_PROGRESS, this.onResourceProgress, this);
            RES.removeEventListener(RES.ResourceEvent.ITEM_LOAD_ERROR, this.onItemLoadError, this);
            this.createGameScene();
        }
    }

/////////////////////////////////////////////

 private createGameScene(){
        var _myGrid:GridSprite = new GridSprite();  
        this.addChild( _myGrid );
    }

then we will got a incorrenct  filled grid not the same as the grid in 
http://edn.egret.com/cn/docs/page/108

![image](https://user-images.githubusercontent.com/11652469/32822976-1b582250-ca16-11e7-895b-ec9f45f0627d.png)

**Comment by himuil** [comment]
This is a Chrome browser bug, other browsers is OK.

**Comment by c19** [comment]
anyone reported the bug to chrome?
