### ISSUE TITLE
关于eui.Scroller中viewport的bug

### ISSUE THREAD

**Issue by anUglyOldDog** [egret-labs/egret-core#204]
我们的场景是一个聊天界面,使用`eui.Scroller`滑动,将`DataGroup`实例指向到`Scroller.viewport`.
现在我们需要打开界面就将聊天 __列表置底__ ,就会出现bug.
用`contentHeight`获取`DataGroup`的高度一直不对.
> 尝试`DataGroup`列表高度超过 *4000px* 应该就会必现.

**Comment by himuil** [comment]
有可能是延迟渲染导致的，你可以尝试用validateNow，或者setTimeout延迟一下

**Comment by anUglyOldDog** [comment]
我环境都说得很明白了,既然你们不当成bug解决就算了吧.反正我们要换成Laya了

**Comment by himuil** [comment]
哪里不当成bug了，不是提供解决方案让您尝试一下了么？我哪句表达的不太对么？
