### ISSUE TITLE
5.1.2引擎有问题

### ISSUE THREAD

**Issue by catechuman** [egret-labs/egret-core#213]
1.自定义的字体文件，即使预加载了，BitmapLabel在编辑器里面可以显示，浏览器中运行是无法显示的

2.没有预加载的sheet文件集，在使用的时候会报错误，但是不影响游戏正常玩。错误原因是在使用的时候回检测是否存在这个资源，但是png资源并没有加载呢，所以直接报了错误，但是会继续执行，异步加载图片之后又显示出来了，我觉得这个错误没必要爆出来。

3.极速骨骼动画会报错。（下载了最新的骨骼文件补丁之后，骨骼动画不显示）

4.有一个疑问，就是platform文件是需要我们自己维护还是官方会把一些必要的微信api提供出来？

**Comment by himuil** [comment]
1.这个问题5.1.3修复了，可以试试
2.这个等5.1.4发布之后可以再试试
3.极速格式报错问题5.1.3修复了
4.我们之后会出一些api对应的.d.ts文件

**Comment by panlimin** [comment]
@WanderWang 现在都5.2.9了，建议关闭该问题
