### ISSUE TITLE
直接传“资源id”可以，但是传“纹理集.资源id”返回null

### ISSUE THREAD

**Issue by Here21** [egret-labs/egret-core#217]
引擎版本 `5.1.3`

**Comment by himuil** [comment]
已经修复，提交到5.1.x分支了：https://github.com/egret-labs/egret-core/commit/500ed565a777be8bad35ccc34eaa47dd90f790e1
可以等更新5.1.4版本

**Comment by Here21** [comment]
谢谢官方团队，辛苦了
