### ISSUE TITLE
新版本assetsmanager里的  ResourceItem 可以加上 loaded 方法吗？

### ISSUE THREAD

**Issue by jet6666** [egret-labs/egret-core#218]
RES是有这方法 的

用作检查GROUP里有哪些没加载成功很有用~~~麻烦加上
`        /**
         * 资源组加载失败
         */

        private onResourceLoadError(e: RES.ResourceEvent): void {
            let list: Array<string> = [];
            RES.getGroupByName(e.groupName).forEach(resItem => {
               if (!resItem.loaded) {
                    list.push(resItem.url);
                }
            });
            App.trace(e.groupName + "资源组有资源加载失败");
            // this.onResourceLoadComplete(e);
            App.resError("----------资源加载失败", list.join(","));`

**Comment by jet6666** [comment]
@himuil

**Comment by WanderWang** [comment]
@jet6666 这个我们评估一下，原则上，我们尽量保持 RES 与 AssetsManager 完全一致，但是有一些细节我们需要斟酌

**Comment by WanderWang** [comment]
@jet6666 ，我仔细看了一下您的需求，我和您沟通 assetsmanager 的一个重要改变

在RES中，如果开发者加载了一个 group，假设中间有素材加载失败，是会派发 complete 事件的，经过三年多的实践和开发者反馈，我们意识到这其实是个很糟糕的设计，所以说，现在在 assetsmanager 里，loadGroup 如果中间存在着加载失败，是会发出error 而不是 complete事件的，所以您这个需求就变得不存在了

**Comment by jet6666** [comment]
意思是加载失败的单个文件信息是得不到吗?

看新版本有抛出加载失败的异常, 意思要去查看那个就可以了?

**Comment by WanderWang** [comment]
不好意思刚看到，是这样的 @jet6666
