### ISSUE TITLE
Event.create bug？

### ISSUE THREAD

**Issue by windreamlion** [egret-labs/egret-core#219]
当创建不同事件类型的时候，会把上一次事件的对象池的内容带上。

**Comment by eos3tion** [comment]
@windreamlion
如果是继承`egret.Event`的自定义事件，如果是在`data`之外新增了变量，应该自行扩展`clean`方法进行清理，白鹭的事件处理，只会清理 `data` `target` `currentTarget`。

**Comment by windreamlion** [comment]
@eos3tion 这个bug是出现在内部提高的touchEvent上
