### ISSUE TITLE
RES.loadConfig(arg1,arg2)   arg2被当作每个资源项url相对路径的基址，但是执行的时候并没有进行赋值

### ISSUE THREAD

**Issue by Rapliangle** [egret-labs/egret-core#222]
function loadConfig(url, resourceRoot) {
        if (url) {
            RES.setConfigURL(url);
        }
        if (!instance)
            instance = new Resource();
        return instance.loadConfig();
    }
    RES.loadConfig = loadConfig;

如上是编译后js的loadConfig方法 ，在ResourceConfig.prototype.init依然是resourceRoot: "resource"写死的情况，如果不是Wing构建项目，而是在其他项目引入的情况，第二个参数就会失效导致资源项各种加载不到。。。

**Comment by himuil** [comment]
引擎5.1.5版本解决了这个问题，可以更新试试

**Comment by Rapliangle** [comment]
我自己把源码里改了在用，只是把问题提上来了 谢谢
