### ISSUE TITLE
Line Dash 显示bug, 设置过一次虚线后, 所有画线都成虚线了

### ISSUE THREAD

**Issue by gaokun** [egret-labs/egret-core#223]
@himuil 你好, 我在使用`lineStyle`的`lineDash`属性时, 遇到了bug: 设置一个line为虚线后, 其他所有的线, 都变成了虚线.
经调查, 原因是画线用的context是共用的(drawDisplayObject方法层层渲染时将context一直传下去), line的其他属性都在画之前, 设置了默认值. 而`lineDash`却没有.

想提交个PR, 所以仔细查看了change log, 看到了在最初添加line dash功能时, 是有重置lineDash属性的.
```js
                if(lineDash) {
                    this.strokePath.setLineDash(lineDash);
                }
                else {
                    this.strokePath.setLineDash([]);
                }
```
但后来fix bug, 又将else去掉了:
```js
                if(lineDash) {
                    this.strokePath.setLineDash(lineDash);
                }
```

**请问是修复什么bug?**

下面是change log的截图

谢谢
Ken

![image](https://user-images.githubusercontent.com/7044628/35469630-ba00202e-0373-11e8-8819-24792fbdda1a.png)

**Comment by himuil** [comment]
非常感谢反馈，https://github.com/egret-labs/egret-core/commit/5d51dce79617c90b440aee9c17a1541f67741016 这次提交修复了这个问题
