### ISSUE TITLE
WebPlayer.updateScreenSize在容器display为none时计算屏幕尺寸为非法值

### ISSUE THREAD

**Issue by Raykid** [egret-labs/egret-core#225]
有时会需要将Egret容器div的display设置为none，此时如果触发页面resize事件会执行WebPlayer.updateScreenSize方法，但getBoundingClientRect方法返回的结构内容都是0，导致Egret计算屏幕尺寸出现NaN，Egret也并未对非法值进行判断和处理，再次显示Egret时无法正常显示。

已经验证出问题的版本为5.0.x，5.1.x没有试过，请修复。

**Comment by himuil** [comment]
非常感谢反馈，这里确实有问题
这次提交修复了这个bug：https://github.com/egret-labs/egret-core/commit/21892da96a2a837f6bd27ed56db6d9537b9115cc
顺便说一下，引擎没有监听设置display的事件，所以在设置该属性之后需要调用一次`egret.updateAllScreens();`来更新一下显示，否则会有异常
