### ISSUE TITLE
关于UILayer里面私有函数的疑问

### ISSUE THREAD

**Issue by QinZhiNian** [egret-labs/egret-core#229]
自己开发的exml组件中，需要在被移除舞台的时候做一些清理工作，如果在constructor中监听移除事件，如果对象没有被添加到舞台中，那么监听的那个事件永远也不可能触发，事件监听也永远不可能被移除，后来仔细查看了代码，发现UILayer中有onAddToStage，onRemoveFromStage，onResize，但是属性是保护的，我不理解为什么要这样私有，如果属性是保护，完全可以通过继承，然后重写来实现添加到舞台的时候初始化，被移除的时候清理，或者舞台尺寸改变的时候调整，也许是我的开发思路有问题，我总觉得这三个函数应该是保护属性

**Comment by QinZhiNian** [comment]
永远也不会触发的监听事件会导致内存泄漏和cpu占用的把

**Comment by himuil** [comment]
如果对象没有被添加到舞台，那么它的createChildren函数就不会被调用，那也不会涉及到清理工作了

**Comment by QinZhiNian** [comment]
是我的观念问题，我认为js增加了监听事件，就算用户对对象失去引用了，但是因为监听了对象事件，后台依然会保持一个引用，但事实上用户失去对象的引用，监听的事件也会释放，是这样的么？

**Comment by himuil** [comment]
@QinZhiNian 内存释放这块可以看看相关的文章，正常使用egret如果不是放到一个全局事件监听器里面，都是可以正常释放的。可以使用chrome调试查看有没有正常内存释放
