### ISSUE TITLE
Trash pixel on screen when multiple objects move simultaneously

### ISSUE THREAD

**Issue by Uno22** [egret-labs/egret-core#234]
![screenshot_20180310-211610](https://user-images.githubusercontent.com/26854902/37243204-74bbb31a-24a8-11e8-8ee9-aedf5eec68c4.png)
Does anyone meet this case?
How to resolve it?

**Comment by himuil** [comment]
What is the engine version?

**Comment by KBTTung** [comment]
@himuil: version 5.0.14, Do you know how to fix? or which version doesn't happen?
