### ISSUE TITLE
特殊的 UserAgnet 导致游戏黑屏

### ISSUE THREAD

**Issue by gangzhiwang** [egret-labs/egret-core#236]
今天在ios的一个APP 中加载游戏 发现 UserAgnet 被修改为iphone 到时候下面这段代码 抛错异常
       

 /**
             * @private
             * 获取ios版本
             * @returns {string}
             */
            Html5Capatibility.getIOSVersion = function () {
                var value = Html5Capatibility.ua.toLowerCase().match(/cpu [^\d]*\d.*like mac os x/)[0];
                return parseInt(value.match(/\d+(_\d)*/)[0]) || 0;
            };

Html5Capatibility.ua.toLowerCase().match(/cpu [^\d]*\d.*like mac os x/) 这段代码 返回为null 直接获取[0] 导致异常 黑屏

**Comment by himuil** [comment]
非常感谢反馈，我们将在新版本加上这里的容错

**Comment by himuil** [comment]
https://github.com/egret-labs/egret-core/commit/f7b4ad91e6212f9d13d4de8413f4e1b5f952ee47
已增加容错，感谢反馈
