### ISSUE TITLE
5.1.x，使用command line出現missing appdata path

### ISSUE THREAD

**Issue by vinceycy** [egret-labs/egret-core#238]
Enviroment
CentOS
node version 6.9.1

create時出現
Scan the project list
Creating a new project folder ...
Compiling the project ...
Egret project is created, you can execute "Egret run" to run the project
(node:230) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): missing appdata path

clean, build時出現
Scan the project list
missing appdata path
Compilation fails

相同情況在5.0.x以下皆不會發生

**Comment by talentyao** [comment]
额 我也是同样的问题，忘尽快修复
