### ISSUE TITLE
对Res.getResByUrl()方法的改进建议

### ISSUE THREAD

**Issue by 502110983** [egret-labs/egret-core#241]
Res.getResByUrl()方法，在不传type的情况下，如果url里带有?v=0111类似这种，此方法回掉方法里返回的竟然是二进制数据，而不是希望的图片之类的资源。
经查看源码，如果不传type，egret会自动根据getTypeByUrl这个方法来判断，但只是简单的根据 . 号来分割字符串来判断文件类型，没有考虑到url后面会带有类似这样的：?v=0111。因为h5的游戏，资源一般都是走cdn的，如果要更新哪个资源，肯定是加版本号来控制的。
如果不看源码，Res.getResByUrl()方法 会让开发者在开发的时候很困扰的，都不知道哪里错误了。

**Comment by runinspring** [comment]
感谢反馈，已经加入该功能
