### ISSUE TITLE
Web:TextField 行数多的时候，webgl下文本会变得模糊(纵向),canvas下正常

### ISSUE THREAD

**Issue by qiwucwb** [egret-labs/egret-core#243]
ver_5.0.* ~ 5.1.*+ 好像都有这个问题
行数越多越明显，手机上比电脑明显。
可以随便写个有TextField的test

append多次容易出现内存暴涨，然后浏览器就爆炸了

**Comment by himuil** [comment]
目前文本的绘制是要先画到一个纹理上的，webgl对纹理最大宽高有限制，所以当超出限制之后引擎会缩放到限制之内。这样就出现了模糊现象，目前可以将太多行的文本拆分成若干个文本规避一下
