### ISSUE TITLE
对可视对象设置matrix，a或者d有负值后，再设置scaleX或者scaleY产生显示不正确的问题

### ISSUE THREAD

**Issue by eos3tion** [egret-labs/egret-core#245]
在任意已经运行的白鹭实例中，执行如下代码
```javascript
var shape = new egret.Shape()
shape.touchEnabled=true;
shape.on(egret.TouchEvent.TOUCH_TAP,doClick);
var g=shape.graphics;
g.beginFill(0xff0000,1);g.moveTo(0,0);g.lineTo(100,100);g.lineTo(-100,100);g.lineTo(0,0);g.endFill();
egret.sys.$TempStage.addChild(shape)
shape.matrix = new egret.Matrix(1,0,0,-1,200,200);
console.log(shape.scaleY);// -1
//此时三角形是朝上的

/**
* 单击三角形
**/
function doClick(){
   console.log("click");
    shape.scaleY=shape.scaleY;
    //此时三角形朝下
   console.log(shape.scaleY);//结果还是 -1
}
```

我比对 `5.1.x` 和 `5.0.x` 代码
5.0.x scaleX和scaleY的设置，会先做是否和当前值相同的判断，如果相同就不进行设值。
但是5.1.x 这个判断去掉了。

但是这个改动应该不是问题的关键，应该是 DisplayObject的 $getMatrix 本身有问题
因为如果把 shape.scaleY = shape.scaleY*.9;
不管是5.0.x还是5.1.x都会出现方向改变的问题。

目前测试下来，只有当 DisplayObject.matrix设值 a和 d 没有负值的情况下，后续设值 scaleX或者scaleY才能正常

**Comment by himuil** [comment]
https://github.com/egret-labs/egret-core/commit/e35a8d74fd2b28633ba41391c6702bed273c6b30
这次提交修复了这个bug，非常感谢反馈
