### ISSUE TITLE
5.0.15 设置TileLayout的 horizontalAlign 为 center不居中

### ISSUE THREAD

**Issue by tqxie** [egret-labs/egret-core#247]
从4.1.1升级到5.0.15，TileLayout中的item不居中了

**Comment by himuil** [comment]
TileLayout的horizontalAlign作用是对齐单元格内的元素，对整体布局是没有影响的，可以参考文档：http://developer.egret.com/cn/apidoc/index/name/eui.TileLayout#horizontalAlign

最开始确实也是不影响整体居中的，后来一个引擎版本引入了这个bug，后续5.0的一个版本修复了这个问题。

整体居中目前没有对应的属性，可以先写个自定义布局去实现一下。
