### ISSUE TITLE
5.1.9在linux下执行报错

### ISSUE THREAD

**Issue by talentyao** [egret-labs/egret-core#252]
[test]# egret create aaa
您正在使用白鹭编译器 5.1.9 版本
Scan the project list
Creating a new project folder ...
Compiling the project ...
Egret project is created, you can execute "Egret run" to run the project
[test]# ls
aaa
[test]# egret build aaa
您正在使用白鹭编译器 5.1.9 版本
Compiling the project ...
missing appdata path
Compilation fails
[test]# egret run 
您正在使用白鹭编译器 5.1.9 版本
Compiling the project ...
"/home/.hudson/jobs/qunying_client_test/workspace/test/" is not a valid Egret project folder
        Egret_Project                   //project folder
                --template              //template folder
                --libs                  //library folder
                --resource              //resource folder
                --src                   //source code folder
                --egretProperties.json  //project configuration file
                --index.html            //launcher file
[test]# egret run aaa
您正在使用白鹭编译器 5.1.9 版本
Compiling the project ...
missing appdata path
Compilation fails
[test]# egret build aaa
您正在使用白鹭编译器 5.1.9 版本
Compiling the project ...
missing appdata path
Compilation fails
[test]#

**Comment by enger816** [comment]
手动从pc  egretlauncher 下载到引擎拷贝过去
