### ISSUE TITLE
egret.Video.pause() API有BUG

### ISSUE THREAD

**Issue by ChoChik** [egret-labs/egret-core#255]
经多位网友测试（包括本人），引擎4.0.3之后的版本，egret.Video.pause()接口，画面会暂停但实际视频并未暂停。
原贴：http://bbs.egret.com/thread-29775-1-1.html

麻烦官方技术修复，多谢

**Comment by leitwolf** [comment]
我今天遇到了，看了源码，源码(354行)并没有让 this.video.pause()
