### ISSUE TITLE
5.1.x里RenamePlugin并没有对sheet的json里面的file进行修改

### ISSUE THREAD

**Issue by haolinchen1991** [egret-labs/egret-core#259]
如题，最终导致发布时当a_sheet_XXXXX.json下回来后，json里面的file字段a_sheet.png因404导致资源加载不出来（此时default.res里面a_sheet.png已经被修改为a_sheet_YYYYY.png了）

**Comment by himuil** [comment]
这里推荐使用assetsmanager，assetsmanager是通过name来加载png文件的，比如json文件对应的name是a_sheet_json，name加载器回去加载a_sheet_png对应的图片资源。资源的name是固定的，url变成什么都无所谓了
