### ISSUE TITLE
ubuntu linux, egret run xxx,but missing appdata path

### ISSUE THREAD

**Issue by bangbaoshi** [egret-labs/egret-core#263]
我的开发环境是linux,
使用的egret-core版本是5.2.0

egret create game之后，
执行egret run 会出现
missing appdata path

原因已经找到，
在run.js中把
toolsList = project_1.launcher.getLauncherLibrary().getInstalledTools();
这一行注释掉即可，

如果你也遇到，希望对你有用

**Comment by runinspring** [comment]
thanks
