### ISSUE TITLE
Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by ZixiaoWang** [egret-labs/egret-core#272]
用 assetmanager 的 loadConfig 方法时，会出现这个问题。
在加载部分 res.json 时候，RES.queue.loadResource(configItem) 并没有返回 Promise类型，而是返回了 undefined。

**Comment by ZixiaoWang** [comment]
RES.loadConfig 对同一资源加载两次（或两次以上）时会出现这个问题。
每次loadConfig时，会生成一个新的configItem并传入 RES.queue.loadResource。之后会在configItem 中加入一个 promise 的属性并在 RES.host.state 中注册。
但如果重复调用 RES.loadConfig，则每次传入 RES.queue.loadResource 的是新的不包含 promise 属性的 configItem 实例。然而在 RES.host.state 中此资源已被注册为“包含promise属性”。
所以加载同一个资源时，会报出 "Cannot read property 'then' of undefined" 错误。

**Comment by Moretai** [comment]
@ZixiaoWang @ZixiaoWang I met same.did you  sloved it ?

**Comment by runinspring** [comment]
can you provide a simple demo so that we can solve the problem @Moretai
