### ISSUE TITLE
请问5.2.3的打包问题

### ISSUE THREAD

**Issue by foezzy** [egret-labs/egret-core#274]
请问5.2.3下，在launcher里的微端打包和直接发布成Android项目有什么不同，还有直接打包成Android后能不能跟之前一样放一些资源在本地，打开后不用去下载的

**Comment by himuil** [comment]
使用最新的EgretLauncher（1.0.60版本），微端和发布Android使用的是同一个runtime内核，在runtime模式下除了api没有区别，微端多了一个webview模式
这块可以参考一下最新的文档：
http://developer.egret.com/cn/github/egret-docs/Native/native/projectsetting/index.html
http://developer.egret.com/cn/github/egret-docs/Native/native/microclient/index.html

**Comment by panlimin** [comment]
@WanderWang 都5.2.9了，建议关闭该问题
