### ISSUE TITLE
不规则裁剪

### ISSUE THREAD

**Issue by lunaticnotcrazy** [egret-labs/egret-core#279]
现在有不规则裁剪图片的接口么?
想完成一个功能是;
将一张大图进行 不规则 裁剪 成多张小图
不知道如何实现 现在有这种接口么

**Comment by himuil** [comment]
可以用RenderTexture+mask

**Comment by danny00lo** [comment]
RenderTexture+mask 感觉没有用，假如两个图形有透明区域，会导致透明区域无法重叠

**Comment by himuil** [comment]
mask是不规则遮罩，专门处理一下透明区域就好了

**Comment by lunaticnotcrazy** [comment]
RenderTexture+mask 基本能实现但是 canvas画图形出现了bug就暂时先放弃了

**Comment by eos3tion** [comment]
@himuil 建议你们合并我提交的 #224 否则`不规则裁剪`还是挺难处理

**Comment by runinspring** [comment]
感谢反馈，那个 pullRequest  我们近期会看下
