### ISSUE TITLE
我想在egret里面增加一个控件，用于显示解码出来的YUV格式的视频数据

### ISSUE THREAD

**Issue by JinYing123** [egret-labs/egret-core#283]
之前尝试共用一个context来渲染视频数据
，结果是屏幕会闪，看来只能在egret里面增加一个控件，用于显示解码出来的YUV格式的视频数据，但是现在完全没有头绪，不知道应该怎么做
![context](https://user-images.githubusercontent.com/41279954/42744180-1c15ae0a-88fd-11e8-8b16-ce143ac47f89.jpg)

**Comment by himuil** [comment]
屏幕闪应该是设置的帧频不是60，设置为60试试
