### ISSUE TITLE
[v-5.2.5] 自动更新的文件，可否每次更新内容模式固定？

### ISSUE THREAD

**Issue by qinhanlei** [egret-labs/egret-core#288]
一些文件每次运行会自动更新，但是内容无非就是顺序变动了而已。
但是 git 上却会产生 modification，为提交和协作造成一定的干扰。

现在 libs/exml.e.d.ts , manifest.json 可以自动生成，可移除并添加到 git ignore 中去。
但是 default.thm.json 却没法自动生成。

希望官方把这些自动生成的东西，能按照确定的顺序排列一下。
我们使用的是 mac，windows 上也有类似的情况

**Comment by oncebet** [comment]
这个问题好烦的 希望官方解决下

**Comment by himuil** [comment]
default.thm.json顺序随机变化的bug已经在最新master分支上修复了，非常感谢反馈

**Comment by qinhanlei** [comment]
@himuil 
嗨，相同的问题 libs/exml.e.d.ts , manifest.json 如果方便的话也修复一下吧

**Comment by himuil** [comment]
@qinhanlei 
你好，libs/exml.e.d.ts的排序是和default.thm.json一致的，5.2.8版本应该已经修复了。manifest.json的排序问题现在master分支已经修复，可以等更新5.2.9版本
