### ISSUE TITLE
5.3.0 编译失败

### ISSUE THREAD

**Issue by south-tree** [egret-labs/egret-core#289]
> egret build
您正在使用白鹭编译器 5.3.0 版本
正在编译项目...
  Error D:/e3workspace/helloworld/egret3d/bin/egret3d.d.ts (485,11): Duplicate identifier 'Color'.
  Error D:/e3workspace/helloworld/egret3d/bin/egret3d.d.ts (729,11): Duplicate identifier 'Quaternion'.
  Error D:/e3workspace/helloworld/egret3d/bin/egret3d.d.ts (784,11): Duplicate identifier 'Rectangle'.
  Error D:/e3workspace/helloworld/egret3d/bin/egret3d.d.ts (956,11): Duplicate identifier 'EventDispatcher'.
  Error D:/e3workspace/helloworld/egret3d/bin/egret3d.d.ts (977,16): Duplicate identifier 'LightType'.
  Error D:/e3workspace/helloworld/egret3d/bin/egret3d.d.ts (3250,11): Duplicate identifier 'Texture'.
  Error D:/e3workspace/helloworld/egret3d/bin/egret3d.d.ts (3496,11): Duplicate identifier 'Mesh'.
  Error D:/e3workspace/helloworld/egret3d/bin/egret3d.d.ts (4078,11): Class 'CameraSystem' incorrectly extends base class 'BaseSystem'.
  Types of property '_interests' are incompatible.
    Type '({ componentClass: typeof Camera; }[] | { componentClass: typeof DirectLight[]; }[])[]' is not assignable to type 'ReadonlyArray<InterestConfig> | ReadonlyArray<ReadonlyArray<InterestConfig>>'.
      Type '({ componentClass: typeof Camera; }[] | { componentClass: typeof DirectLight[]; }[])[]' is not assignable to type 'ReadonlyArray<ReadonlyArray<InterestConfig>>'.
        Types of property 'concat' are incompatible.
          Type '{ (...items: ({ componentClass: typeof Camera; }[] | { componentClass: typeof DirectLight[]; }[])...' is not assignable to type '{ (...items: ReadonlyArray<InterestConfig>[][]): ReadonlyArray<InterestConfig>[]; (...items: (Rea...'.
            Types of parameters 'items' and 'items' are incompatible.
              Type 'ReadonlyArray<InterestConfig>[]' is not assignable to type '({ componentClass: typeof Camera; }[] | { componentClass: typeof DirectLight[]; }[])[]'.
                Type 'ReadonlyArray<InterestConfig>' is not assignable to type '{ componentClass: typeof Camera; }[] | { componentClass: typeof DirectLight[]; }[]'.
                  Type 'ReadonlyArray<InterestConfig>' is not assignable to type '{ componentClass: typeof DirectLight[]; }[]'.
                    Property 'push' is missing in type 'ReadonlyArray<InterestConfig>'.
  Error D:/e3workspace/helloworld/egret3d/bin/egret3d.d.ts (4759,11): Duplicate identifier 'DirectLight'.
  Error D:/e3workspace/helloworld/egret3d/bin/egret3d.d.ts (4769,11): Duplicate identifier 'PointLight'.
  Error D:/e3workspace/helloworld/egret3d/bin/egret3d.d.ts (4779,11): Duplicate identifier 'SpotLight'.
  Error D:/e3workspace/helloworld/egret3d/bin/egret3d.d.ts (5670,11): Cannot redeclare block-scoped variable 'Stage3D'.
  Error D:/e3workspace/helloworld/egret3d/bin/egret3d.d.ts (5771,11): Duplicate identifier 'Ray'.
  Error D:/e3workspace/helloworld/egret3d/bin/egret3d.d.ts (6648,11): Class 'WebGLRenderSystem' incorrectly extends base class 'BaseSystem'.
  Types of property '_interests' are incompatible.
    Type '({ componentClass: typeof Camera; }[] | { componentClass: typeof Egret2DRenderer; }[] | { compone...' is not assignable to type 'ReadonlyArray<InterestConfig> | ReadonlyArray<ReadonlyArray<InterestConfig>>'.
      Type '({ componentClass: typeof Camera; }[] | { componentClass: typeof Egret2DRenderer; }[] | { compone...' is not assignable to type 'ReadonlyArray<ReadonlyArray<InterestConfig>>'.
        Types of property 'concat' are incompatible.
          Type '{ (...items: ({ componentClass: typeof Camera; }[] | { componentClass: typeof Egret2DRenderer; }[...' is not assignable to type '{ (...items: ReadonlyArray<InterestConfig>[][]): ReadonlyArray<InterestConfig>[]; (...items: (Rea...'.
            Types of parameters 'items' and 'items' are incompatible.
              Type 'ReadonlyArray<InterestConfig>[]' is not assignable to type '({ componentClass: typeof Camera; }[] | { componentClass: typeof Egret2DRenderer; }[] | { compone...'.
                Type 'ReadonlyArray<InterestConfig>' is not assignable to type '{ componentClass: typeof Camera; }[] | { componentClass: typeof Egret2DRenderer; }[] | { componen...'.
                  Type 'ReadonlyArray<InterestConfig>' is not assignable to type '{ componentClass: typeof DirectLight[]; }[]'.
                    Property 'push' is missing in type 'ReadonlyArray<InterestConfig>'.
  Error D:/e3workspace/helloworld/egret3d/bin/egret3d.d.ts (6799,11): Class 'GlRenderTarget' incorrectly implements interface 'IRenderTarget'.
  Property 'useMipmap' is missing in type 'GlRenderTarget'.
  Error D:/e3workspace/helloworld/egret3d/bin/egret3d.d.ts (6812,11): Class 'GlRenderTargetCube' incorrectly implements interface 'IRenderTarget'.
  Property 'useMipmap' is missing in type 'GlRenderTargetCube'.
  Error D:/e3workspace/helloworld/egret3d/bin/egret3d.d.ts (6829,11): Class 'GlTexture2D' incorrectly implements interface 'ITexture'.
  Property 'useMipmap' is missing in type 'GlTexture2D'.
  Error D:/e3workspace/helloworld/egret3d/bin/egret3d.d.ts (6847,11): Class 'WriteableTexture2D' incorrectly implements interface 'ITexture'.
  Property 'useMipmap' is missing in type 'WriteableTexture2D'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (6,11): Cannot redeclare block-scoped variable 'webAssemblyModule'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (18,9): Duplicate identifier 'WeigthBoneCount'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (19,9): Duplicate identifier 'WeigthFloatOffset'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (20,9): Duplicate identifier 'WeigthBoneIndices'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (21,9): Duplicate identifier 'MeshVertexCount'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (22,9): Duplicate identifier 'MeshTriangleCount'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (23,9): Duplicate identifier 'MeshFloatOffset'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (24,9): Duplicate identifier 'MeshWeightOffset'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (25,9): Duplicate identifier 'MeshVertexIndices'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (26,9): Duplicate identifier 'TimelineScale'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (27,9): Duplicate identifier 'TimelineOffset'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (28,9): Duplicate identifier 'TimelineKeyFrameCount'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (29,9): Duplicate identifier 'TimelineFrameValueCount'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (30,9): Duplicate identifier 'TimelineFrameValueOffset'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (31,9): Duplicate identifier 'TimelineFrameOffset'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (32,9): Duplicate identifier 'FramePosition'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (33,9): Duplicate identifier 'FrameTweenType'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (34,9): Duplicate identifier 'FrameTweenEasingOrCurveSampleCount'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (35,9): Duplicate identifier 'FrameCurveSamples'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (36,9): Duplicate identifier 'FFDTimelineMeshOffset'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (37,9): Duplicate identifier 'FFDTimelineFFDCount'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (38,9): Duplicate identifier 'FFDTimelineValueCount'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (39,9): Duplicate identifier 'FFDTimelineValueOffset'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (40,9): Duplicate identifier 'FFDTimelineFloatOffset'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (46,9): Duplicate identifier 'Armature'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (47,9): Duplicate identifier 'MovieClip'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (48,9): Duplicate identifier 'Stage'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (54,9): Duplicate identifier 'Image'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (55,9): Duplicate identifier 'Armature'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (56,9): Duplicate identifier 'Mesh'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (57,9): Duplicate identifier 'BoundingBox'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (65,9): Duplicate identifier 'Rectangle'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (66,9): Duplicate identifier 'Ellipse'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (67,9): Duplicate identifier 'Polygon'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (73,9): Duplicate identifier 'Play'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (74,9): Duplicate identifier 'Frame'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (75,9): Duplicate identifier 'Sound'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (81,9): Duplicate identifier 'Normal'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (82,9): Duplicate identifier 'Add'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (83,9): Duplicate identifier 'Alpha'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (84,9): Duplicate identifier 'Darken'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (85,9): Duplicate identifier 'Difference'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (86,9): Duplicate identifier 'Erase'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (87,9): Duplicate identifier 'HardLight'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (88,9): Duplicate identifier 'Invert'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (89,9): Duplicate identifier 'Layer'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (90,9): Duplicate identifier 'Lighten'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (91,9): Duplicate identifier 'Multiply'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (92,9): Duplicate identifier 'Overlay'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (93,9): Duplicate identifier 'Screen'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (94,9): Duplicate identifier 'Subtract'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (100,9): Duplicate identifier 'None'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (101,9): Duplicate identifier 'Line'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (102,9): Duplicate identifier 'Curve'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (103,9): Duplicate identifier 'QuadIn'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (104,9): Duplicate identifier 'QuadOut'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (105,9): Duplicate identifier 'QuadInOut'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (111,9): Duplicate identifier 'Action'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (112,9): Duplicate identifier 'ZOrder'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (113,9): Duplicate identifier 'BoneAll'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (114,9): Duplicate identifier 'BoneTranslate'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (115,9): Duplicate identifier 'BoneRotate'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (116,9): Duplicate identifier 'BoneScale'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (117,9): Duplicate identifier 'SlotDisplay'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (118,9): Duplicate identifier 'SlotColor'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (119,9): Duplicate identifier 'SlotFFD'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (120,9): Duplicate identifier 'AnimationTime'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (121,9): Duplicate identifier 'AnimationWeight'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (127,9): Duplicate identifier 'None'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (128,9): Duplicate identifier 'Additive'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (129,9): Duplicate identifier 'Override'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (142,9): Duplicate identifier 'None'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (148,9): Duplicate identifier 'SameLayer'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (154,9): Duplicate identifier 'SameGroup'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (160,9): Duplicate identifier 'SameLayerAndGroup'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (166,9): Duplicate identifier 'All'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (172,9): Duplicate identifier 'Single'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (178,9): Duplicate string index signature.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (183,11): Duplicate identifier 'DragonBones'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (207,20): Duplicate identifier 'BaseObject'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (266,11): Duplicate identifier 'Matrix'.
  Error D:/e3workspace/helloworld/libs/modules/assetsmanager/build/dragonBones-wasm/dragonBones.d.ts (335,11): Duplicate identifier 'Transform'.
项目共计编译耗时：27.116秒
编译失败

**Comment by himuil** [comment]
应该是你引擎目录的assetsmanager库出了问题

**Comment by panlimin** [comment]
@south-tree 5.3.0是3d的，建议转到3d项目的issues下[此处](https://github.com/egret-labs/egret3d/issues)
@WanderWang 建议转移该问题
