### ISSUE TITLE
internal 标记前后不一致

### ISSUE THREAD

**Issue by joesonw** [egret-labs/egret-core#304]
https://github.com/egret-labs/egret-core/blob/9ff751cd4093f2f0639e7b91c31dca0a57a72261/src/extension/assetsmanager/src/processor/Processor.ts#L246

为什么 SheetProcessor, XMLProcessor 和 FontProcessor 是internal? 其余的又不是? 随意的?  之前全都是 public

**Comment by eos3tion** [comment]
@joesonw 不要太在意`jsdoc`的`@internal`标记，目前`Typescript`还没`internal`修饰符  
详情看：https://github.com/Microsoft/TypeScript/issues/5228  
另外 用于支持 `jsdoc` 的 ```--declaration --stripInternal``` 目前`ts 3.1.2`的版本也是有bug的，更不用说白鹭目前的ts编译器还停留在`ts2.7`的版本

**Comment by joesonw** [comment]
@eos3tion  会有的, `egret.d.ts`里面是没有这几个定义的. egret.processor. SheetProcessor 是不存在. 只能egret.processor['SheetProcessor'], 这样就失去了typing检查了.

**Comment by runinspring** [comment]
感谢反馈
