### ISSUE TITLE
通过Egret Launchar工具使用5.3.1引擎版本创建项目的问题

### ISSUE THREAD

**Issue by oyjq** [egret-labs/egret-core#308]
通过Egret Launchar工具使用5.3.1引擎版本创建项目，发布时候在微信工具预览时候出现图中问题。
![wechatimg2081](https://user-images.githubusercontent.com/9411473/47774185-440d8580-dd27-11e8-98be-4fa940422d3a.jpeg)

**Comment by runinspring** [comment]
暂时不支持5.3版本的引擎创建微信小游戏项目
