### ISSUE TITLE
Must restart the PC in order to get the environment setup?

### ISSUE THREAD

**Issue by jcs090218** [egret-labs/egret-core#310]
Hi, thank you for all your hard work. I just want to report an issue I acknowledge immediately after I installed Egret Wing, when I first installed it then the environment path seems not to setup correctly because I am not able to open the project with this software right after I installed it. Furthermore, I am not sure if this is the appropriate behaviour because the installer seems does not mention anything that you must restart your PC in order to get the software run correctly. I think the solution should fairly straightforward, peace.

Environment Informations: 
OS: `Windows 10`
Egret Launcher Version: `5.2.10`
Egret Wing 3 Version: `4.1.6`

**Comment by runinspring** [comment]
Thanks

**Comment by jcs090218** [comment]
Great to help out this amazing project! Keep it up! :D
