### ISSUE TITLE
微信小游戏中使用egret.WebSocket无法连接服务器

### ISSUE THREAD

**Issue by xigalto** [egret-labs/egret-core#315]
如题，如果使用微信小游戏自带的wx.connectSocket是可以连接的，看了下egret.WebSocket的源码应该是没有对这个做兼容，考虑加进去下么？要不得维护两套不同的socket或者不使用egret.WebSocket。

**Comment by runinspring** [comment]
可以提供复现的demo吗，我们测试是可以使用websocket的

**Comment by xigalto** [comment]
这个我都快忘记了，后来发现好像是因为在小游戏里使用ip地址连不上，换成域名后可以了
