### ISSUE TITLE
5.2.10 IE浏览器加载音频可能不派发事件

### ISSUE THREAD

**Issue by LangZhai** [egret-labs/egret-core#317]
https://github.com/egret-labs/egret-core/commit/7cc45146d77ccef1ee5284694e6d76e6289d6147#commitcomment-31509886
这个问题在IE中也存在，所以除了判断ua包含'edge'之外，还应该判断包含'trident'。

**Comment by runinspring** [comment]
在5.2.15上已经修复了该问题，您可以试一下

**Comment by LangZhai** [comment]
> 在5.2.15上已经修复了该问题，您可以试一下

我看到你修改的代码依然是判断ua上是否存在"edge"，但是你的注释却是说解决IE11的声音加载问题，然而IE11的ua上其实是没有"edge"的，为什么这样判断呢？我很困惑。

**Comment by runinspring** [comment]
感谢反馈，上次修改是解决`edge`浏览器的问题。后续我们会加上 trident 的判断

**Comment by LangZhai** [comment]
> 感谢反馈，上次修改是解决`edge`浏览器的问题。后续我们会加上 trident 的判断

好的，谢谢！

**Comment by runinspring** [comment]
该问题已经在 5.2.15_fix 分支上修复，或者等 5.2.16 正式版发布。

**Comment by LangZhai** [comment]
> 该问题已经在 5.2.15_fix 分支上修复，或者等 5.2.16 正式版发布。

谢谢，那这个Issue我先关了。
