### ISSUE TITLE
在egert 能否使用aixos等异步请求

### ISSUE THREAD

**Issue by czkm** [egret-labs/egret-core#326]

**Comment by WanderWang** [comment]
这个问题的本质问题是，是否可以在 egret 中使用 npm install 命令安装的第三方库。

在长期以来这个答案都是No，但是经过团队努力，这个问题即将在 2月底得到彻底的改变，具体情况请耐心稍等几天

**Comment by czkm** [comment]
谢谢开发者，目前大多使用自己分装的https类库
