### ISSUE TITLE
新安装Egret Paper运行后提示未找到paper-cli

### ISSUE THREAD

**Issue by ylkx2008** [egret-labs/egret-core#327]
刚安装完Egret Paper，运行后提示未找到paper-cli

**Comment by DirtyWhite** [comment]
请打开任意命令行 执行  npm i paper-cli -g

**Comment by luguosheng1314** [comment]
安装后打开还是报这个错

**Comment by iClassic-Live** [comment]
无法使用该命令行安装paper脚手架，报错日志如下

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'paper-cli',
1 verbose cli   '-g' ]
2 info using npm@6.4.1
3 info using node@v10.14.1
4 verbose npm-session 2aecdc8a0904d5d1
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 404 https://registry.npmjs.org/paper-cli 830ms
8 silly fetchPackageMetaData error for paper-cli@latest 404 Not Found: paper-cli@latest
9 timing stage:rollbackFailedOptional Completed in 4ms
10 timing stage:runTopLevelLifecycles Completed in 1039ms
11 verbose stack Error: 404 Not Found: paper-cli@latest
11 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
11 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
11 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
11 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
11 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
11 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
11 verbose stack     at runCallback (timers.js:705:18)
11 verbose stack     at tryOnImmediate (timers.js:676:5)
11 verbose stack     at processImmediate (timers.js:658:5)
12 verbose cwd C:\Users\YW1587
13 verbose Windows_NT 10.0.16299
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "paper-cli" "-g"
15 verbose node v10.14.1
16 verbose npm  v6.4.1
17 error code E404
18 error 404 Not Found: paper-cli@latest
19 verbose exit [ 1, true ]

**Comment by runinspring** [comment]
3D的问题，请在这边提 https://github.com/egret-labs/egret3d ，会有同事解答，谢谢。
