### ISSUE TITLE
js文件加载顺序有问题

### ISSUE THREAD

**Issue by sid-ihycq** [egret-labs/egret-core#328]
编译时候是对的，运行的时候，namespace里面有直接执行初始化的代码，引用到了别的namespace中的函数，加载顺序不正确导致namespace是not defined！！可以看到manifest.json中生成的代码确实js文件顺序不正确！加上三斜线指令< reference >也没用
5.2.15版本，5.2.13也是。
请尽快解决😭😭😭

**Comment by runinspring** [comment]
近期我们会推出一种新的工程结构，会彻底解决排序问题

**Comment by jason-grimm** [comment]
> 编译时候是对的，运行的时候，namespace里面有直接执行初始化的代码，引用到了别的namespace中的函数，加载顺序不正确导致namespace是not defined！！可以看到manifest.json中生成的代码确实js文件顺序不正确！加上三斜线指令< reference >也没用
> 5.2.15版本，5.2.13也是。
> 请尽快解决😭😭😭

个人建议还是写到模块里吧，namespace编译出来就是个普通Object，本身不能变量提升，感觉怎么解决都会有不严谨的情况。😂

**Comment by sid-ihycq** [comment]
> > 编译时候是对的，运行的时候，namespace里面有直接执行初始化的代码，引用到了别的namespace中的函数，加载顺序不正确导致namespace是not defined！！可以看到manifest.json中生成的代码确实js文件顺序不正确！加上三斜线指令< reference >也没用
> > 5.2.15版本，5.2.13也是。
> > 请尽快解决😭😭😭
> 
> 个人建议还是写到模块里吧，namespace编译出来就是个普通Object，本身不能变量提升，感觉怎么解决都会有不严谨的情况。😂

跟模块没有关系吧，就算是写成模块也会有互相依赖的初始化代码，总不能每个模块留一个init到main里面再调用吧……

**Comment by sid-ihycq** [comment]
> > > > 编译时候是对的，运行的时候，namespace里面有直接执行初始化的代码，引用到了别的namespace中的函数，加载顺序不正确导致namespace是not defined！！可以看到manifest.json中生成的代码确实js文件顺序不正确！加上三斜线指令< reference >也没用
> > > > 5.2.15版本，5.2.13也是。
> > > > 请尽快解决😭😭😭
> > > 
> > > 
> > > 个人建议还是写到模块里吧，namespace编译出来就是个普通Object，本身不能变量提升，感觉怎么解决都会有不严谨的情况。😂
> > 
> > 
> > 跟模块没有关系吧，就算是写成模块也会有互相依赖的初始化代码，总不能每个模块留一个init到main里面再调用吧……
> 
> 是的，写成模块也不能完全避免，但是会大大降低概率，模块的导出会尽量调整导出顺序，namespace纯粹就是字母顺序排列的...

还不如像cocos一样手动定义加载顺序，我已经放弃之前的写法了：namespace和module里面尽量只是数据和纯函数而不依赖外部，实在需要就留个init；尽量写全局的class，全局的对象尽量多用延迟初始化，不然构造函数有可能因为依赖问题执行失败。
