### ISSUE TITLE
5.3.2创建的项目报错

### ISSUE THREAD

**Issue by 305371179** [egret-labs/egret-core#330]
使用Pro来创建的项目，一开始就报错了，这是郁闷。Uncaught ReferenceError: exports is not defined     at (/Users/gsch/Desktop/游戏/Egret3DTest/bin-debug/behaviours/RotateBehaviour.js:18:23)

**Comment by runinspring** [comment]
请在3D项目里提 Issues，便于同事解答，谢谢。https://github.com/egret-labs/egret3d
