### ISSUE TITLE
修复getTimer被攻击的可能

### ISSUE THREAD

**Issue by xinfangke** [egret-labs/egret-core#332]
建议修改getTimer.ts的实现方式，避免被本地调整时间造成的一些恶意攻击

    export function getTimer():number {
        return (window.performance && window.performance.now && window.performance.timing && window.performance.timing.navigationStart ? window.performance.now() + window.performance.timing.navigationStart : Date.now()) - sys.$START_TIME;
    }

sys.$START_TIME 也做适当修改

**Comment by eos3tion** [comment]
@xinfangke javascript就不要考虑靠这种手段防止攻击了，直接注入脚本就完了，替换performance都可以。服务端该做的验证做好。

**Comment by xinfangke** [comment]
@eos3tion 还是有必要的，这种不处理，会造成很多意想不到的问题。

如:

时区的调整，可能会影响到运行时的判定。 

用户调整时间，可能会影响到运行时的判定。 

这种攻击都不是针对性的，引擎本身要提供一种比较稳定的运行时间。

**Comment by eos3tion** [comment]
@xinfangke 你是想防止误操作，还是防止恶意改动？想防止恶意改动是不可能防止的  
如果只是想防止误操作的话，到没啥问题，我自己这边如果只是简单改白鹭的东西都是直接用注入方式替换白鹭方法的。
你让白鹭官方做  
`window.performance`这种写法，他们`native`都未必支持，还有各种`小游戏`环境
他官方肯定不会这样写的
你直接在你项目里面做
```ts
egret.getTimer = function():number {
    return (window.performance && window.performance.now && window.performance.timing && window.performance.timing.navigationStart ? window.performance.now() + window.performance.timing.navigationStart : Date.now()) - sys.$START_TIME;
}
```

**Comment by xinfangke** [comment]
@eos3tion 我目前是这样做的，但是这不是友好的方案。

至于白鹭是不是要修改，看他们了，问题是存在的。

至于native白鹭是单独实现的。

小游戏的是独立适配处理的，即使小游戏没有window.performance，上诉的逻辑依然会正常走Date

**Comment by xinfangke** [comment]
zz
