### ISSUE TITLE
egret.Timer，egret.Ticker 脱离DisplayObject的生命周期，这需要逼着自己维护删除吗？

### ISSUE THREAD

**Issue by MR-L-2015** [egret-labs/egret-core#351]

**Comment by MR-L-2015** [comment]
某L引擎有的。在Node.timeLoop, timeOnce等地方。但我不知道它的实现是否跟着Node的生命周期了。

**Comment by eos3tion** [comment]
@MR-L-2015 说实话，Timer，Ticker需要和DisplayObject有关系么？我一个后台服务用Timer，Ticker不行么？

**Comment by MR-L-2015** [comment]
Timer Ticker还是独立的，但是DisplayObject我觉得它应该维护自己的Timer，该Timer由它的父亲驱动。如果DisplayObject被删除了，那些已经安排运行的对应该DisplayObject的Timer应该自动失效的意思，这样就不用自己维护Timer的生命周期。

例如不小心开了几个无限循环Timer，切换DisplayObjectContainer，舞台，场景等之后，会存在那些Timer还在后台跑得欢的问题。游戏做复杂了，这些需要开发人员搽屁股的事情越少越好。

**Comment by MR-L-2015** [comment]
还有那些类似于塔防加速x2 x4的游戏，没有这套DisplayObjectContainer管理子DisplayObject一切吃喝拉撒的机制，相当于把引擎的共有功能被逼带到每个团队中去做，每个团队能力也有限，也费劲。
