### ISSUE TITLE
能否考虑给DisplayObject添加一个百分比的anchor操作函数，这个比较常用

### ISSUE THREAD

**Issue by MR-L-2015** [egret-labs/egret-core#354]
cocos2d-x 里面的锚点是百分比0到1表示0%到100%的。
如果DisplayObject添加一个锚点类型枚举=pixel, percent的区分，然后通过
anchorOffsetX, anchorOffsetY实现像素定位或者百分比定位，就更加理想了。

**Comment by eos3tion** [comment]
@MR-L-2015 这种理论上应该封装到`layout`操作，或者是EUI那边有这些是没有问题，底层`DisplayObject`不应该有这些，甚至`白鹭`现在的封装，我都嫌`太重`。

**Comment by MR-L-2015** [comment]
@eos3tion 我觉得egret的优势在于开源，但把自己定位为渲染引擎非常难理解，你们官网宣传都不错的呀，90%都是游戏，事实摆着那里呀。
Unity，某C，某L加其编辑器，某E加其EUI之类的，开发起游戏都有一个通病，就是功能驱动输入可能是来源于手写代码，也可能是来源于资源拖拽，维护起来老费劲了。这种思路我觉得不能发挥小游戏需要容易上手，和需要容易维护的特点。
大制作不愁这些，小制作我觉得cocos2d-x v2的那种思路好使，纯代码思路，上手快试错快才能更好响应市场，市场能成功关键不是拥有雷布斯而是拥有乔布斯。

**Comment by eos3tion** [comment]
@MR-L-2015 其实是这个意思，就是你觉得很爽的display要有你说的timer，而我的游戏项目里面从来不这样写。你想要封装进去觉得很爽，但是我会觉得很不爽。事实就是还有很多不同想法的开发者，代码就应该分层分的干净。而且js算是最容易做mixin的语言，ts又为mixin带来了类型支持，你想要的功能，只用把DisplayObject.prototype直接外部扩展，或者直接做mixin即可。

**Comment by MR-L-2015** [comment]
谢谢
