### ISSUE TITLE
ByteArray解码utf8的"\0"字符问题

### ISSUE THREAD

**Issue by lhkzh** [egret-labs/egret-core#358]
src/egret/utils/ByteArray.ts
1093行
if (code_point > 0) result += String.fromCharCode(code_point);
改为
if (code_point >= 0) result += String.fromCharCode(code_point);

**Comment by eos3tion** [comment]
@lhkzh  这个问题，白鹭不想改的，要兼容`flash`的设定
https://github.com/egret-labs/egret-core/issues/192

**Comment by lhkzh** [comment]
@eos3tion   哦哦。好吧，还有这原因啊。
