### ISSUE TITLE
Typo or design?

### ISSUE THREAD

**Issue by sxd1140** [egret-labs/egret-core#364]
https://github.com/egret-labs/egret-core/blob/f4865a31fc3673d6bd636d3ca0ba51d1c62e973b/src/egret/display/BitmapData.ts#L193

https://github.com/egret-labs/egret-core/blob/f4865a31fc3673d6bd636d3ca0ba51d1c62e973b/src/egret/display/BitmapData.ts#L196

**Comment by xrdavies** [comment]
Seems typo

**Comment by runinspring** [comment]
Thanks
