### ISSUE TITLE
bash: egret: command not found

### ISSUE THREAD

**Issue by fattigerlee** [egret-labs/egret-core#370]
我在windows上安装了egret,使用windows cmd和powershell执行egret命令成功,但是使用git bash执行egret提示bash: egret: command not found,请问是什么原因?使用的引擎版本是5.2.30.

**Comment by eos3tion** [comment]
你git bash的的`.bashrc`没有相应执行指令，你参考 Linux 运行 egret 这篇文章调整一下就可以了
https://blog.csdn.net/u010797947/article/details/46881571

**Comment by fattigerlee** [comment]
谢谢,已解决,贴上解决方案,方面后面的同学.
.bashrc里面添加已下配置:

```
alias egret="/C/Users/maker/AppData/Roaming/npm/egret.cmd"
```
