### ISSUE TITLE
How I canfix this error?

### ISSUE THREAD

**Issue by AreyKiy** [egret-labs/egret-core#374]
" Error: #1. Net error, please try again later. "

How I can fix it?

![image](https://user-images.githubusercontent.com/28147596/71327482-9dc7a500-2511-11ea-83d3-aad051a0534d.png)

**Comment by a22aaass** [comment]
where can show this window again?i never see it in egret

**Comment by tejudivate** [comment]
Even I am facing the same issue

**Comment by sxd1140** [comment]
Install the new version of `DragonBones Pro`.

**Comment by YellowAfterlife** [comment]
Updating does not seem to have any effect, not even grabbing the 5.6.2 installer from a direct URL, not even trying to grab a 5.6.3 installer by editing the URL (which gives you a 5.6.2 installer still, unfortunately). Registering gives a JSON error, logging in gives a net error. Using a VPN makes no difference. Everyone loves trying out a piece of software and losing work right away, that'll keep them stick around for later

**Comment by runinspring** [comment]
You can use the full features of DB pro  without logging in now
