### ISSUE TITLE
Facing this log-in issue

### ISSUE THREAD

**Issue by tejudivate** [egret-labs/egret-core#375]
This error comes up when I try to log-in. I tried resetting the password but then again facing another error.

![dragonbones bug2](https://user-images.githubusercontent.com/16590646/71577915-00c1c900-2b1c-11ea-8dd8-5297634722f9.png)
![dragonbones bug](https://user-images.githubusercontent.com/16590646/71577917-00c1c900-2b1c-11ea-8ad0-90c8c64acd54.png)

**Comment by sxd1140** [comment]
#374

**Comment by eos3tion** [comment]
upgrade to v3.6.2

**Comment by runinspring** [comment]
You can use the full features of DB pro  without logging in now
