### ISSUE TITLE
更新了iOS13.4 beta iOS Native不能用了

### ISSUE THREAD

**Issue by ccimage** [egret-labs/egret-core#376]
更新了iOS13.4 beta
iOS Native不能用了
iOS13.4目前是beta版，3月份开始推送更新

disableNativeRender=true 黑屏
1:ERROR:attachShader attachShader error
1:ERROR:attachShader attachShader error
1:JS:INFO:Error: #1025

disableNativeRender=false 闪退
:1:ERROR:customRender render root is nullptr

**Comment by runinspring** [comment]
该问题已经在Native 1.0.1 版本中修复，多谢反馈
