### ISSUE TITLE
compile error with libs define codes contains "getter" or "setter"

### ISSUE THREAD

**Issue by ccimage** [egret-labs/egret-core#377]
if define file *.d.ts of libs contains getter or setter.  
run egret build shows error

 An accessor cannot be declared in an ambient context.

link to code lines in *.d.ts as
 private set isReady(value: boolean);
 private get isReady():boolean;

-----------

**Comment by runinspring** [comment]
Egret's built-in TypeScript compiler doesn't support this feature yet
