### ISSUE TITLE
在 wsl 中无法运行 egret 命令

### ISSUE THREAD

**Issue by coppyC** [egret-labs/egret-core#380]
我在windows 中安装了 egret 命令
但是在 wsl 中无法运行 egret.cmd 命令
![image](https://user-images.githubusercontent.com/25004510/84470126-3535d580-acb5-11ea-8be7-e28fe4ae2b98.png)

请问 如何在 wsl 在使用 egret ，或者如何在 linux 中安装 egret 。

**Comment by YangShuangjie** [comment]
将 egret-core下载到你的wsl中（比如放在家目录下），然后添加环境变量
# egeret
# export PATH=$HOME/egret-core/tools/bin:$PATH
