### ISSUE TITLE
此引擎是否還有人在維護

### ISSUE THREAD

**Issue by scott20145** [egret-labs/egret-core#427]
想請問egret原始碼開放修改嗎,有沒有官方的人可說明

有沒有人對於改善引擎有想法的可以交流一下

目前基於5.3.10版本 自己已實現
純webpack編譯流(非官方版本)
1. hdr支援
2. bloom支援
3. 多材質支援
4. 龍骨draw call 優化

**Comment by wuweixing3** [comment]
团队都解散了。联系不上官方的人员。是否可以自己建立一个仓库

**Comment by a22aaass** [comment]
什么事吖

**Comment by scott20145** [comment]
> 团队都解散了。联系不上官方的人员。是否可以自己建立一个仓库

其實egret 核心蠻完善
目前包成APP版, 效能也都頗順暢
不再維護確實可惜些

**Comment by a22aaass** [comment]
什么事吖
