### ISSUE TITLE
有没有机会把官网的开发者文档开源一下？

### ISSUE THREAD

**Issue by ccimage** [egret-labs/egret-core#431]
还没备份就已经打不开了

**Comment by mqflive** [comment]
方便大家下载egret软件，写了一个下载页 ：https://egret.pages.dev/（记得保存收藏)

**Comment by ccimage** [comment]
但是没有文档了

**Comment by mqflive** [comment]
确实，等有缘人修复吧

**Comment by developerworks** [comment]
文档可以打开, 只是 HTTPS 的证书失效了

<img width="1229" alt="image" src="https://github.com/egret-labs/egret-core/assets/725190/76f0ce19-d5bb-421a-9681-758a96abed7b">

**Comment by mqflive** [comment]
怎么打开的

**Comment by ccimage** [comment]
太好了 我已经克隆整个文档
运行就能克隆
wget -m --no-check-certificate https://docs.egret.com/engine/docs/build/introduction
