### ISSUE TITLE
什么时候支持linux？

### ISSUE THREAD

**Issue by YowaiCoder** [egret-labs/egret-core#62]
现在手动把egret目录提取出来，加了环境变量，然后发现build完了不能运行，egret的文件没有加载出来，看了半天源码发现 egret/tools/lib/tools/compile.js里第504行有一句：
var tsFile = file.joinPath(moduleConfig.prefix, moduleConfig.source, item).toLowerCase();

这句把源码文件路径转成了小写，linux是区分大小写的，所以后面没读到文件内容，结果所有文件都被当成了只含接口，没有加到egret_file_list.js里去。去掉.toLowerCase()后就正常了。

粗略看了一下还有好多地方都是这样用的，不知道还有没有需要改的。

以后打算支持linux吗？

**Comment by sg552** [comment]
Linux 不是主流操作系统吗.... 哎....
