### ISSUE TITLE
卸载 Egret 1.5.5 时卡住 

### ISSUE THREAD

**Issue by davinma** [egret-labs/egret-core#76]
操作系统：win7 64位旗舰版
Egret 版本： 1.5.5

卸载 Egret 时遭遇假死，查看进程 EgretAppManager 和 EgretScriptManager，然后统统关掉。在
> C:\Users\youname\AppData\Roaming\Egret\script\Error.txt

中发现原因是无法覆盖 Adobe AIR.dll 文件。

几经周折，在 command.txt 文件中发现了这么一行：
> run "bin/wscript.exe" "C:\Users\youname\AppData\Roaming\EgretAppManager\Local Store\uninstall.vbs"

估计是跟卸载脚本有关，于是双击之。于是神奇的一幕出现了，桌面的 Egret Engine 图标消失了。然后其他的几个程序也都好卸载了。

在此感谢 3 群 egret-xsstomy 大大和他同事们的帮助。

**Comment by zerlot** [comment]
如果还遇到这样的问题，可以直接找我们。
