### ISSUE TITLE
iPhone Safari 经常性渲染漏掉一些DisplayObject

### ISSUE THREAD

**Issue by ErrorCode233** [egret-labs/egret-core#80]
可以是egret.TextField, 也可以是egret.gui.SkinnableContainer, 随机性很强。是内存不够造成？Profiler显示的渲染个数110~120左右

**Comment by zerlot** [comment]
我安排团队排查一下

**Comment by himuil** [comment]
我们目前没有遇到过类似的问题呢，请更新到最新版本试试问题是否还会存在，要是还存在可以加我qq：892246460
