### ISSUE TITLE
package.json 版本号与实际不符

### ISSUE THREAD

**Issue by Lanfei** [egret-labs/egret-core#81]
当前版本号是 1.7.2，*package.json* 中的版本号是 1.7.3，导致 `egret info` 命令获取的版本号也不正确了。

**Comment by himuil** [comment]
egret info输出的是你当前使用的引擎版本号，你更新到哪个版本的引擎那么就是哪个版本的版本号

**Comment by Lanfei** [comment]
是的，我更新到 GitHub 最新的版本，也就是 1.7.2，但输出的版本号是 1.7.3。

**Comment by WanderWang** [comment]
这个原因是您下载的引擎master版本，而那个版本刚好正在变动中
