### ISSUE TITLE
resource.json groups中的内容需要拆成多行

### ISSUE THREAD

**Issue by miaodadao** [egret-labs/egret-core#85]
`groups`中的内容最好采用多行记录，方便团队多人同时工作，对版本管理工具更友好。现在超长的单行记录几乎每次都会冲突，几乎无法合并，几乎总要有人重复再做一次。
如果考虑运行时效率，可以在最终发布脚本中做紧缩合并。

**Comment by featherJ** [comment]
您说的有道理，但是目前keys的类型为字符串，在格式上并不是很好拆分成多行。 我们先考虑下这个事情的解决方案。 感谢您提出的问题 : )

**Comment by miaodadao** [comment]
`keys`的解析代码改为既可以适配`string[ ]`*(直接拿来用就好了)*，也可以适配`string`*(老版本的，逗号分隔解析后再用)*，然后新版本的工具直接生成`string[ ]`格式并完美换行即可
