### ISSUE TITLE
egret和bat脚本兼容有问题

### ISSUE THREAD

**Issue by miaodadao** [egret-labs/egret-core#86]
bat中执行以下脚本：
```bat
egret publish
pause
```
在egret命令执行完之后bat即被杀掉，后面的`pause`根本没有机会执行。也就是说无法用egret顺畅的组成脚本管线，一旦遇到egret就会被掐断。

**Comment by miaodadao** [comment]
需要在调用`egret`前加上`call`就可解决：
```bat
call egret publish
pause
```

希望官方修改下默认的bat模板

**Comment by WanderWang** [comment]
感谢反馈
