### ISSUE TITLE
ByteArray不支持Runtime/Native环境。

### ISSUE THREAD

**Issue by mzszhznn** [egret-labs/egret-core#88]
目前我做的东西都是通过ByteArray解析的，突然发现api文档里说不支持Runtime/Native环境。
这个什么时候能支持，等回复！

**Comment by h-wei** [comment]
@mzszhznn，ByteArray的支持在v1.6的时候就已经完善了，我们要去检查一下api文档，谢谢指出

**Comment by mzszhznn** [comment]
是加载文件BinAnalyzer模块的，加载后转成ByteArray方式解析，昨天看到文档说不支持的问题问了一下city，他说webSocket是支持的，加载到本地后转成ByteArray的不支持。

**Comment by domchen** [comment]
现在已经支持了，感谢反馈~

**Comment by mzszhznn** [comment]
@domchen 经过测试，网络加载回来的首次结果放回的是string类型。缓存到客户端后，第二次直接客户端读取是正常的。

**Comment by mzszhznn** [comment]
另外jszip模块打包进后再native下获取不到，我手动修改了jszip将类引入global后可以获取。调用jszip解析文件时，会报一个uint8Array相关的错。

**Comment by WanderWang** [comment]
请问是否可以提供一下你的代码，我们重现一下

**Comment by mzszhznn** [comment]
demo已经发到您QQ邮箱了！
