### ISSUE TITLE
Video issue  width and height would be zero when running on browser

### ISSUE THREAD

**Issue by leon456** [egret-labs/egret-core#95]
var video:egret.Video = new egret.Video();
        video.src = "http://www.quirksmode.org/html5/videos/big_buck_bunny.ogv";
        video.width = 600;
        video.height = 300;
        this.addChild(video);
        video.play();
![qq 20150922182216](https://cloud.githubusercontent.com/assets/365520/10016077/e86e8d86-6156-11e5-838f-d4d1e73e9dc2.png)

**Comment by runinspring** [comment]
we had fied it in 2.5.5
